// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iotmsg/rpcmsg.proto

package iotmsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Timestamp from public import google/protobuf/timestamp.proto
type Timestamp = timestamp.Timestamp

//import public "google/protobuf/any.proto";
//import public "google/protobuf/struct.proto";
type RpcHead struct {
	Kvmap                map[string]string `protobuf:"bytes,1,rep,name=kvmap,proto3" json:"kvmap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RpcHead) Reset()         { *m = RpcHead{} }
func (m *RpcHead) String() string { return proto.CompactTextString(m) }
func (*RpcHead) ProtoMessage()    {}
func (*RpcHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f8db75737c1df, []int{0}
}

func (m *RpcHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcHead.Unmarshal(m, b)
}
func (m *RpcHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcHead.Marshal(b, m, deterministic)
}
func (m *RpcHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcHead.Merge(m, src)
}
func (m *RpcHead) XXX_Size() int {
	return xxx_messageInfo_RpcHead.Size(m)
}
func (m *RpcHead) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcHead.DiscardUnknown(m)
}

var xxx_messageInfo_RpcHead proto.InternalMessageInfo

func (m *RpcHead) GetKvmap() map[string]string {
	if m != nil {
		return m.Kvmap
	}
	return nil
}

type Void struct {
	Head                 *RpcHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Seq                  int32    `protobuf:"varint,2,opt,name=Seq,proto3" json:"Seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f8db75737c1df, []int{1}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func (m *Void) GetHead() *RpcHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *Void) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type RpcResponse struct {
	Code   int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Errmsg string `protobuf:"bytes,3,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	//    google.protobuf.Struct JsonData = 4;
	JsonData             string   `protobuf:"bytes,4,opt,name=JsonData,proto3" json:"JsonData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcResponse) Reset()         { *m = RpcResponse{} }
func (m *RpcResponse) String() string { return proto.CompactTextString(m) }
func (*RpcResponse) ProtoMessage()    {}
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f8db75737c1df, []int{2}
}

func (m *RpcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcResponse.Unmarshal(m, b)
}
func (m *RpcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcResponse.Marshal(b, m, deterministic)
}
func (m *RpcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcResponse.Merge(m, src)
}
func (m *RpcResponse) XXX_Size() int {
	return xxx_messageInfo_RpcResponse.Size(m)
}
func (m *RpcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcResponse proto.InternalMessageInfo

func (m *RpcResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RpcResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RpcResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *RpcResponse) GetJsonData() string {
	if m != nil {
		return m.JsonData
	}
	return ""
}

type StatusModel struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusModel) Reset()         { *m = StatusModel{} }
func (m *StatusModel) String() string { return proto.CompactTextString(m) }
func (*StatusModel) ProtoMessage()    {}
func (*StatusModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f8db75737c1df, []int{3}
}

func (m *StatusModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusModel.Unmarshal(m, b)
}
func (m *StatusModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusModel.Marshal(b, m, deterministic)
}
func (m *StatusModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusModel.Merge(m, src)
}
func (m *StatusModel) XXX_Size() int {
	return xxx_messageInfo_StatusModel.Size(m)
}
func (m *StatusModel) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusModel.DiscardUnknown(m)
}

var xxx_messageInfo_StatusModel proto.InternalMessageInfo

func (m *StatusModel) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type IdModel struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdModel) Reset()         { *m = IdModel{} }
func (m *IdModel) String() string { return proto.CompactTextString(m) }
func (*IdModel) ProtoMessage()    {}
func (*IdModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f8db75737c1df, []int{4}
}

func (m *IdModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdModel.Unmarshal(m, b)
}
func (m *IdModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdModel.Marshal(b, m, deterministic)
}
func (m *IdModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdModel.Merge(m, src)
}
func (m *IdModel) XXX_Size() int {
	return xxx_messageInfo_IdModel.Size(m)
}
func (m *IdModel) XXX_DiscardUnknown() {
	xxx_messageInfo_IdModel.DiscardUnknown(m)
}

var xxx_messageInfo_IdModel proto.InternalMessageInfo

func (m *IdModel) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IdModel) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type UUIdModel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UUIdModel) Reset()         { *m = UUIdModel{} }
func (m *UUIdModel) String() string { return proto.CompactTextString(m) }
func (*UUIdModel) ProtoMessage()    {}
func (*UUIdModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f8db75737c1df, []int{5}
}

func (m *UUIdModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UUIdModel.Unmarshal(m, b)
}
func (m *UUIdModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UUIdModel.Marshal(b, m, deterministic)
}
func (m *UUIdModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UUIdModel.Merge(m, src)
}
func (m *UUIdModel) XXX_Size() int {
	return xxx_messageInfo_UUIdModel.Size(m)
}
func (m *UUIdModel) XXX_DiscardUnknown() {
	xxx_messageInfo_UUIdModel.DiscardUnknown(m)
}

var xxx_messageInfo_UUIdModel proto.InternalMessageInfo

func (m *UUIdModel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UUIdModel) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ModelTime struct {
	CreatedAt            string   `protobuf:"bytes,1,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,2,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelTime) Reset()         { *m = ModelTime{} }
func (m *ModelTime) String() string { return proto.CompactTextString(m) }
func (*ModelTime) ProtoMessage()    {}
func (*ModelTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f8db75737c1df, []int{6}
}

func (m *ModelTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelTime.Unmarshal(m, b)
}
func (m *ModelTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelTime.Marshal(b, m, deterministic)
}
func (m *ModelTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelTime.Merge(m, src)
}
func (m *ModelTime) XXX_Size() int {
	return xxx_messageInfo_ModelTime.Size(m)
}
func (m *ModelTime) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelTime.DiscardUnknown(m)
}

var xxx_messageInfo_ModelTime proto.InternalMessageInfo

func (m *ModelTime) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ModelTime) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*RpcHead)(nil), "iotmsg.RpcHead")
	proto.RegisterMapType((map[string]string)(nil), "iotmsg.RpcHead.KvmapEntry")
	proto.RegisterType((*Void)(nil), "iotmsg.Void")
	proto.RegisterType((*RpcResponse)(nil), "iotmsg.RpcResponse")
	proto.RegisterType((*StatusModel)(nil), "iotmsg.StatusModel")
	proto.RegisterType((*IdModel)(nil), "iotmsg.IdModel")
	proto.RegisterType((*UUIdModel)(nil), "iotmsg.UUIdModel")
	proto.RegisterType((*ModelTime)(nil), "iotmsg.ModelTime")
}

func init() { proto.RegisterFile("iotmsg/rpcmsg.proto", fileDescriptor_5f9f8db75737c1df) }

var fileDescriptor_5f9f8db75737c1df = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdd, 0x6b, 0xdb, 0x30,
	0x14, 0xc5, 0x67, 0xc7, 0x4e, 0xe6, 0x6b, 0xd8, 0x86, 0x36, 0x36, 0xcf, 0x0c, 0x16, 0x3c, 0x06,
	0x79, 0x99, 0x3d, 0xb2, 0x97, 0x30, 0xd8, 0xc3, 0xbe, 0xd8, 0x47, 0x29, 0x14, 0xa5, 0xe9, 0x43,
	0xdf, 0x14, 0x4b, 0x71, 0x45, 0xec, 0x48, 0xb5, 0xe4, 0x40, 0xfe, 0xfb, 0xa2, 0x0f, 0x12, 0x68,
	0xe9, 0xdb, 0x3d, 0xbf, 0x73, 0xcf, 0xb9, 0xc2, 0x18, 0x5e, 0x72, 0xa1, 0x3b, 0xd5, 0x54, 0xbd,
	0xac, 0x3b, 0xd5, 0x94, 0xb2, 0x17, 0x5a, 0xa0, 0xb1, 0x83, 0xf9, 0xfb, 0x46, 0x88, 0xa6, 0x65,
	0x95, 0xa5, 0xeb, 0x61, 0x53, 0x69, 0xde, 0x31, 0xa5, 0x49, 0x27, 0xdd, 0x62, 0x31, 0xc0, 0x04,
	0xcb, 0xfa, 0x2f, 0x23, 0x14, 0x7d, 0x86, 0x78, 0xbb, 0xef, 0x88, 0xcc, 0x82, 0xe9, 0x68, 0x96,
	0xce, 0xf3, 0xd2, 0x75, 0x94, 0xde, 0x2f, 0xcf, 0x8c, 0xf9, 0x7b, 0xa7, 0xfb, 0x03, 0x76, 0x8b,
	0xf9, 0x02, 0xe0, 0x04, 0xd1, 0x0b, 0x18, 0x6d, 0xd9, 0x21, 0x0b, 0xa6, 0xc1, 0x2c, 0xc1, 0x66,
	0x44, 0xaf, 0x20, 0xde, 0x93, 0x76, 0x60, 0x59, 0x68, 0x99, 0x13, 0x5f, 0xc3, 0x45, 0x50, 0x7c,
	0x83, 0xe8, 0x4a, 0x70, 0x8a, 0x3e, 0x40, 0x74, 0xc3, 0x08, 0xb5, 0xa1, 0x74, 0xfe, 0xfc, 0xde,
	0x49, 0x6c, 0x4d, 0x53, 0xbc, 0x64, 0xb7, 0xb6, 0x24, 0xc6, 0x66, 0x2c, 0x1a, 0x48, 0xb1, 0xac,
	0x31, 0x53, 0x52, 0xec, 0x14, 0x43, 0x08, 0xa2, 0x5a, 0x50, 0x66, 0x5b, 0x62, 0x6c, 0x67, 0x13,
	0xea, 0x54, 0xe3, 0x2f, 0x9b, 0x11, 0xbd, 0x86, 0x31, 0xeb, 0x7b, 0x03, 0x47, 0x16, 0x7a, 0x85,
	0x72, 0x78, 0xfa, 0x5f, 0x89, 0xdd, 0x2f, 0xa2, 0x49, 0x16, 0x59, 0xe7, 0xa8, 0x8b, 0x8f, 0x90,
	0x2e, 0x35, 0xd1, 0x83, 0x3a, 0x17, 0x94, 0xb5, 0xa6, 0x42, 0x59, 0xe9, 0x4f, 0x79, 0x55, 0x7c,
	0x82, 0xc9, 0x3f, 0xea, 0x56, 0x9e, 0x41, 0xc8, 0xa9, 0xb7, 0x43, 0x4e, 0x8f, 0x6f, 0x73, 0x0f,
	0xb1, 0x73, 0x51, 0x41, 0xb2, 0x5a, 0x3d, 0x0c, 0x24, 0x8f, 0x06, 0xfe, 0x40, 0x62, 0x97, 0x2f,
	0x79, 0xc7, 0xd0, 0x3b, 0x48, 0x7e, 0xf6, 0x8c, 0x68, 0x46, 0xbf, 0x6b, 0x9f, 0x3b, 0x01, 0xe3,
	0xae, 0x24, 0xf5, 0xae, 0xeb, 0x38, 0x81, 0x1f, 0x6f, 0xaf, 0xdf, 0x34, 0x9b, 0x83, 0xe6, 0x42,
	0xbb, 0x5f, 0xa2, 0xe5, 0xeb, 0xca, 0x7d, 0xf3, 0x8b, 0x27, 0xeb, 0xb1, 0x45, 0x5f, 0xee, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x0c, 0x01, 0x67, 0x85, 0x52, 0x02, 0x00, 0x00,
}
