// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commandService.proto

package pbgocmd

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("commandService.proto", fileDescriptor_2031e321e3f7896b) }

var fileDescriptor_2031e321e3f7896b = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0x09, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x4f, 0x4d, 0x49, 0x4f, 0xcd, 0x2d, 0x4e, 0x97, 0x12, 0x80, 0x4a, 0xfb, 0x16, 0xa7,
	0x43, 0xa4, 0x8c, 0xce, 0x30, 0x72, 0xf1, 0x39, 0xa3, 0xe8, 0x11, 0x32, 0xe3, 0xe2, 0x08, 0x49,
	0x2d, 0x2e, 0x71, 0xce, 0xcf, 0xcb, 0x13, 0x12, 0xd6, 0x83, 0x6a, 0xd5, 0x0b, 0x4e, 0x2d, 0xf4,
	0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x95, 0x42, 0x08, 0x3a, 0x26, 0x67, 0x43, 0x05, 0x95, 0x18,
	0x84, 0x9c, 0xb8, 0xb8, 0x7d, 0x32, 0x41, 0xfa, 0xc0, 0xa6, 0x09, 0x89, 0xc3, 0x55, 0x81, 0x45,
	0x73, 0x53, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0xa4, 0x24, 0x30, 0x25, 0x8a, 0x0b, 0xf2,
	0xf3, 0x8a, 0x41, 0x66, 0xd8, 0x71, 0xb1, 0x63, 0xea, 0x87, 0x8a, 0x60, 0xea, 0x87, 0x4b, 0xc0,
	0xf4, 0x1b, 0xcd, 0x60, 0xe4, 0x12, 0x81, 0x79, 0xa7, 0xa4, 0x28, 0x35, 0x31, 0x97, 0x52, 0x4f,
	0x79, 0x70, 0xf1, 0x42, 0xcd, 0x73, 0x29, 0x2d, 0xc8, 0x49, 0xad, 0x20, 0xcb, 0x59, 0x1a, 0x8c,
	0x06, 0x8c, 0x4e, 0xea, 0x5c, 0xa2, 0x99, 0xf9, 0x25, 0x7a, 0x05, 0x99, 0x7a, 0x49, 0x45, 0xf9,
	0xd9, 0xa9, 0x45, 0x7a, 0xd0, 0xb8, 0x08, 0x60, 0x8c, 0xe2, 0xd4, 0xb3, 0x86, 0xea, 0xed, 0x60,
	0x64, 0x0c, 0x60, 0x48, 0x62, 0x03, 0xc7, 0x8d, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xb6, 0xf0,
	0x2b, 0x5c, 0xce, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommandServiceClient is the client API for CommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommandServiceClient interface {
	// 链接测试, 发送一个int类型随机数,服务端+1 后返回.
	TestConn(ctx context.Context, in *SeqMessage, opts ...grpc.CallOption) (*AckMessage, error)
	//
	ListCommand(ctx context.Context, in *ListCmdRequest, opts ...grpc.CallOption) (*ListCmdResponse, error)
	// 发送一次单向命令
	Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
}

type commandServiceClient struct {
	cc *grpc.ClientConn
}

func NewCommandServiceClient(cc *grpc.ClientConn) CommandServiceClient {
	return &commandServiceClient{cc}
}

func (c *commandServiceClient) TestConn(ctx context.Context, in *SeqMessage, opts ...grpc.CallOption) (*AckMessage, error) {
	out := new(AckMessage)
	err := c.cc.Invoke(ctx, "/edgemsg.CommandService/TestConn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) ListCommand(ctx context.Context, in *ListCmdRequest, opts ...grpc.CallOption) (*ListCmdResponse, error) {
	out := new(ListCmdResponse)
	err := c.cc.Invoke(ctx, "/edgemsg.CommandService/ListCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, "/edgemsg.CommandService/Command", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandServiceServer is the server API for CommandService service.
type CommandServiceServer interface {
	// 链接测试, 发送一个int类型随机数,服务端+1 后返回.
	TestConn(context.Context, *SeqMessage) (*AckMessage, error)
	//
	ListCommand(context.Context, *ListCmdRequest) (*ListCmdResponse, error)
	// 发送一次单向命令
	Command(context.Context, *CommandRequest) (*CommandResponse, error)
}

// UnimplementedCommandServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommandServiceServer struct {
}

func (*UnimplementedCommandServiceServer) TestConn(ctx context.Context, req *SeqMessage) (*AckMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestConn not implemented")
}
func (*UnimplementedCommandServiceServer) ListCommand(ctx context.Context, req *ListCmdRequest) (*ListCmdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCommand not implemented")
}
func (*UnimplementedCommandServiceServer) Command(ctx context.Context, req *CommandRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Command not implemented")
}

func RegisterCommandServiceServer(s *grpc.Server, srv CommandServiceServer) {
	s.RegisterService(&_CommandService_serviceDesc, srv)
}

func _CommandService_TestConn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).TestConn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edgemsg.CommandService/TestConn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).TestConn(ctx, req.(*SeqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_ListCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCmdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).ListCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edgemsg.CommandService/ListCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).ListCommand(ctx, req.(*ListCmdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_Command_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).Command(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edgemsg.CommandService/Command",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).Command(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "edgemsg.CommandService",
	HandlerType: (*CommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestConn",
			Handler:    _CommandService_TestConn_Handler,
		},
		{
			MethodName: "ListCommand",
			Handler:    _CommandService_ListCommand_Handler,
		},
		{
			MethodName: "Command",
			Handler:    _CommandService_Command_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commandService.proto",
}

// CommandStreamServiceClient is the client API for CommandStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommandStreamServiceClient interface {
	// 链接测试, 发送一个int类型随机数,服务端+1 后返回.
	TestConn(ctx context.Context, in *SeqMessage, opts ...grpc.CallOption) (*AckMessage, error)
	// 进行长链接双向通讯命令
	CommandDuplex(ctx context.Context, opts ...grpc.CallOption) (CommandStreamService_CommandDuplexClient, error)
}

type commandStreamServiceClient struct {
	cc *grpc.ClientConn
}

func NewCommandStreamServiceClient(cc *grpc.ClientConn) CommandStreamServiceClient {
	return &commandStreamServiceClient{cc}
}

func (c *commandStreamServiceClient) TestConn(ctx context.Context, in *SeqMessage, opts ...grpc.CallOption) (*AckMessage, error) {
	out := new(AckMessage)
	err := c.cc.Invoke(ctx, "/edgemsg.CommandStreamService/TestConn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandStreamServiceClient) CommandDuplex(ctx context.Context, opts ...grpc.CallOption) (CommandStreamService_CommandDuplexClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CommandStreamService_serviceDesc.Streams[0], "/edgemsg.CommandStreamService/CommandDuplex", opts...)
	if err != nil {
		return nil, err
	}
	x := &commandStreamServiceCommandDuplexClient{stream}
	return x, nil
}

type CommandStreamService_CommandDuplexClient interface {
	Send(*CommandRequest) error
	Recv() (*CommandResponse, error)
	grpc.ClientStream
}

type commandStreamServiceCommandDuplexClient struct {
	grpc.ClientStream
}

func (x *commandStreamServiceCommandDuplexClient) Send(m *CommandRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *commandStreamServiceCommandDuplexClient) Recv() (*CommandResponse, error) {
	m := new(CommandResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CommandStreamServiceServer is the server API for CommandStreamService service.
type CommandStreamServiceServer interface {
	// 链接测试, 发送一个int类型随机数,服务端+1 后返回.
	TestConn(context.Context, *SeqMessage) (*AckMessage, error)
	// 进行长链接双向通讯命令
	CommandDuplex(CommandStreamService_CommandDuplexServer) error
}

// UnimplementedCommandStreamServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommandStreamServiceServer struct {
}

func (*UnimplementedCommandStreamServiceServer) TestConn(ctx context.Context, req *SeqMessage) (*AckMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestConn not implemented")
}
func (*UnimplementedCommandStreamServiceServer) CommandDuplex(srv CommandStreamService_CommandDuplexServer) error {
	return status.Errorf(codes.Unimplemented, "method CommandDuplex not implemented")
}

func RegisterCommandStreamServiceServer(s *grpc.Server, srv CommandStreamServiceServer) {
	s.RegisterService(&_CommandStreamService_serviceDesc, srv)
}

func _CommandStreamService_TestConn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandStreamServiceServer).TestConn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edgemsg.CommandStreamService/TestConn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandStreamServiceServer).TestConn(ctx, req.(*SeqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandStreamService_CommandDuplex_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommandStreamServiceServer).CommandDuplex(&commandStreamServiceCommandDuplexServer{stream})
}

type CommandStreamService_CommandDuplexServer interface {
	Send(*CommandResponse) error
	Recv() (*CommandRequest, error)
	grpc.ServerStream
}

type commandStreamServiceCommandDuplexServer struct {
	grpc.ServerStream
}

func (x *commandStreamServiceCommandDuplexServer) Send(m *CommandResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *commandStreamServiceCommandDuplexServer) Recv() (*CommandRequest, error) {
	m := new(CommandRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CommandStreamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "edgemsg.CommandStreamService",
	HandlerType: (*CommandStreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestConn",
			Handler:    _CommandStreamService_TestConn_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CommandDuplex",
			Handler:       _CommandStreamService_CommandDuplex_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "commandService.proto",
}
