// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commandMsg.proto

package pbgocmd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestAny struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 *any.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestAny) Reset()         { *m = TestAny{} }
func (m *TestAny) String() string { return proto.CompactTextString(m) }
func (*TestAny) ProtoMessage()    {}
func (*TestAny) Descriptor() ([]byte, []int) {
	return fileDescriptor_d005cd91a5b498e7, []int{0}
}

func (m *TestAny) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestAny.Unmarshal(m, b)
}
func (m *TestAny) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestAny.Marshal(b, m, deterministic)
}
func (m *TestAny) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestAny.Merge(m, src)
}
func (m *TestAny) XXX_Size() int {
	return xxx_messageInfo_TestAny.Size(m)
}
func (m *TestAny) XXX_DiscardUnknown() {
	xxx_messageInfo_TestAny.DiscardUnknown(m)
}

var xxx_messageInfo_TestAny proto.InternalMessageInfo

func (m *TestAny) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TestAny) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

// 通用消息头
type MessageHead struct {
	// 消息id
	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// 自定义消息类型
	MsgTypes int32 `protobuf:"varint,2,opt,name=MsgTypes,proto3" json:"MsgTypes,omitempty"`
	// 消息时间, 标准unix时间戳,基于秒单位
	MsgTime int64 `protobuf:"varint,3,opt,name=MsgTime,proto3" json:"MsgTime,omitempty"`
	// 消息有效时间,单位: 毫秒,为0则表示不限制,在两台主机时间与ntp服务器同步一致的情况,
	MsgLiveTime int64 `protobuf:"varint,4,opt,name=MsgLiveTime,proto3" json:"MsgLiveTime,omitempty"`
	// 调用超时时间,单位: 毫秒,为0则表示不限制,如果消息在多个节点进行转发调用时,该字段为每个节点转发调用的所允许的最大超时时长
	CallTimeout int32 `protobuf:"varint,5,opt,name=CallTimeout,proto3" json:"CallTimeout,omitempty"`
	// Extend字段,数据签名
	Sign string `protobuf:"bytes,6,opt,name=Sign,proto3" json:"Sign,omitempty"`
	// 额外控制扩展消息头, 如是否加密, 加密类型,各种id,等信息.
	Extend               map[string]string `protobuf:"bytes,7,rep,name=Extend,proto3" json:"Extend,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MessageHead) Reset()         { *m = MessageHead{} }
func (m *MessageHead) String() string { return proto.CompactTextString(m) }
func (*MessageHead) ProtoMessage()    {}
func (*MessageHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_d005cd91a5b498e7, []int{1}
}

func (m *MessageHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageHead.Unmarshal(m, b)
}
func (m *MessageHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageHead.Marshal(b, m, deterministic)
}
func (m *MessageHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageHead.Merge(m, src)
}
func (m *MessageHead) XXX_Size() int {
	return xxx_messageInfo_MessageHead.Size(m)
}
func (m *MessageHead) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageHead.DiscardUnknown(m)
}

var xxx_messageInfo_MessageHead proto.InternalMessageInfo

func (m *MessageHead) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageHead) GetMsgTypes() int32 {
	if m != nil {
		return m.MsgTypes
	}
	return 0
}

func (m *MessageHead) GetMsgTime() int64 {
	if m != nil {
		return m.MsgTime
	}
	return 0
}

func (m *MessageHead) GetMsgLiveTime() int64 {
	if m != nil {
		return m.MsgLiveTime
	}
	return 0
}

func (m *MessageHead) GetCallTimeout() int32 {
	if m != nil {
		return m.CallTimeout
	}
	return 0
}

func (m *MessageHead) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *MessageHead) GetExtend() map[string]string {
	if m != nil {
		return m.Extend
	}
	return nil
}

// 命令列表请求
type ListCmdRequest struct {
	CmdHead              *MessageHead `protobuf:"bytes,10,opt,name=CmdHead,proto3" json:"CmdHead,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListCmdRequest) Reset()         { *m = ListCmdRequest{} }
func (m *ListCmdRequest) String() string { return proto.CompactTextString(m) }
func (*ListCmdRequest) ProtoMessage()    {}
func (*ListCmdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d005cd91a5b498e7, []int{2}
}

func (m *ListCmdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCmdRequest.Unmarshal(m, b)
}
func (m *ListCmdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCmdRequest.Marshal(b, m, deterministic)
}
func (m *ListCmdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCmdRequest.Merge(m, src)
}
func (m *ListCmdRequest) XXX_Size() int {
	return xxx_messageInfo_ListCmdRequest.Size(m)
}
func (m *ListCmdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCmdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCmdRequest proto.InternalMessageInfo

func (m *ListCmdRequest) GetCmdHead() *MessageHead {
	if m != nil {
		return m.CmdHead
	}
	return nil
}

// 命令结构对象
type Command struct {
	FunctionID           string   `protobuf:"bytes,10,opt,name=FunctionID,proto3" json:"FunctionID,omitempty"`
	Name                 string   `protobuf:"bytes,20,opt,name=Name,proto3" json:"Name,omitempty"`
	Introduce            string   `protobuf:"bytes,30,opt,name=Introduce,proto3" json:"Introduce,omitempty"`
	ArgsInfo             string   `protobuf:"bytes,40,opt,name=ArgsInfo,proto3" json:"ArgsInfo,omitempty"`
	ReturnInfo           string   `protobuf:"bytes,50,opt,name=ReturnInfo,proto3" json:"ReturnInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_d005cd91a5b498e7, []int{3}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetFunctionID() string {
	if m != nil {
		return m.FunctionID
	}
	return ""
}

func (m *Command) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command) GetIntroduce() string {
	if m != nil {
		return m.Introduce
	}
	return ""
}

func (m *Command) GetArgsInfo() string {
	if m != nil {
		return m.ArgsInfo
	}
	return ""
}

func (m *Command) GetReturnInfo() string {
	if m != nil {
		return m.ReturnInfo
	}
	return ""
}

type Service struct {
	SrvId                string     `protobuf:"bytes,10,opt,name=SrvId,proto3" json:"SrvId,omitempty"`
	Name                 string     `protobuf:"bytes,20,opt,name=Name,proto3" json:"Name,omitempty"`
	Introduce            string     `protobuf:"bytes,30,opt,name=Introduce,proto3" json:"Introduce,omitempty"`
	Version              string     `protobuf:"bytes,40,opt,name=Version,proto3" json:"Version,omitempty"`
	NodeInfo             string     `protobuf:"bytes,50,opt,name=NodeInfo,proto3" json:"NodeInfo,omitempty"`
	Cmds                 []*Command `protobuf:"bytes,60,rep,name=Cmds,proto3" json:"Cmds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_d005cd91a5b498e7, []int{4}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetSrvId() string {
	if m != nil {
		return m.SrvId
	}
	return ""
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetIntroduce() string {
	if m != nil {
		return m.Introduce
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Service) GetNodeInfo() string {
	if m != nil {
		return m.NodeInfo
	}
	return ""
}

func (m *Service) GetCmds() []*Command {
	if m != nil {
		return m.Cmds
	}
	return nil
}

// 命令列表响应体
type ListCmdResponse struct {
	CmdHead              *MessageHead `protobuf:"bytes,10,opt,name=CmdHead,proto3" json:"CmdHead,omitempty"`
	Services             []*Service   `protobuf:"bytes,20,rep,name=Services,proto3" json:"Services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListCmdResponse) Reset()         { *m = ListCmdResponse{} }
func (m *ListCmdResponse) String() string { return proto.CompactTextString(m) }
func (*ListCmdResponse) ProtoMessage()    {}
func (*ListCmdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d005cd91a5b498e7, []int{5}
}

func (m *ListCmdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCmdResponse.Unmarshal(m, b)
}
func (m *ListCmdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCmdResponse.Marshal(b, m, deterministic)
}
func (m *ListCmdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCmdResponse.Merge(m, src)
}
func (m *ListCmdResponse) XXX_Size() int {
	return xxx_messageInfo_ListCmdResponse.Size(m)
}
func (m *ListCmdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCmdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCmdResponse proto.InternalMessageInfo

func (m *ListCmdResponse) GetCmdHead() *MessageHead {
	if m != nil {
		return m.CmdHead
	}
	return nil
}

func (m *ListCmdResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

// 命令消息
type CommandRequest struct {
	// 通用消息头,多个message共用.
	CmdHead *MessageHead `protobuf:"bytes,10,opt,name=CmdHead,proto3" json:"CmdHead,omitempty"`
	// 分开传输
	ServiceId            string   `protobuf:"bytes,20,opt,name=ServiceId,proto3" json:"ServiceId,omitempty"`
	FunctionId           string   `protobuf:"bytes,30,opt,name=FunctionId,proto3" json:"FunctionId,omitempty"`
	Param                []byte   `protobuf:"bytes,40,opt,name=Param,proto3" json:"Param,omitempty"`
	InSecureData         []byte   `protobuf:"bytes,50,opt,name=InSecureData,proto3" json:"InSecureData,omitempty"`
	InSecureInfo         string   `protobuf:"bytes,60,opt,name=InSecureInfo,proto3" json:"InSecureInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandRequest) Reset()         { *m = CommandRequest{} }
func (m *CommandRequest) String() string { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()    {}
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d005cd91a5b498e7, []int{6}
}

func (m *CommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandRequest.Unmarshal(m, b)
}
func (m *CommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandRequest.Marshal(b, m, deterministic)
}
func (m *CommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandRequest.Merge(m, src)
}
func (m *CommandRequest) XXX_Size() int {
	return xxx_messageInfo_CommandRequest.Size(m)
}
func (m *CommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommandRequest proto.InternalMessageInfo

func (m *CommandRequest) GetCmdHead() *MessageHead {
	if m != nil {
		return m.CmdHead
	}
	return nil
}

func (m *CommandRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *CommandRequest) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

func (m *CommandRequest) GetParam() []byte {
	if m != nil {
		return m.Param
	}
	return nil
}

func (m *CommandRequest) GetInSecureData() []byte {
	if m != nil {
		return m.InSecureData
	}
	return nil
}

func (m *CommandRequest) GetInSecureInfo() string {
	if m != nil {
		return m.InSecureInfo
	}
	return ""
}

// 命令结果
type CommandResponse struct {
	// 通用消息头,多个message共用.
	CmdHead              *MessageHead `protobuf:"bytes,10,opt,name=CmdHead,proto3" json:"CmdHead,omitempty"`
	Code                 int32        `protobuf:"varint,20,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string       `protobuf:"bytes,30,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 []byte       `protobuf:"bytes,40,opt,name=Data,proto3" json:"Data,omitempty"`
	InSecureData         []byte       `protobuf:"bytes,50,opt,name=InSecureData,proto3" json:"InSecureData,omitempty"`
	InSecureInfo         string       `protobuf:"bytes,60,opt,name=InSecureInfo,proto3" json:"InSecureInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CommandResponse) Reset()         { *m = CommandResponse{} }
func (m *CommandResponse) String() string { return proto.CompactTextString(m) }
func (*CommandResponse) ProtoMessage()    {}
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d005cd91a5b498e7, []int{7}
}

func (m *CommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandResponse.Unmarshal(m, b)
}
func (m *CommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandResponse.Marshal(b, m, deterministic)
}
func (m *CommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandResponse.Merge(m, src)
}
func (m *CommandResponse) XXX_Size() int {
	return xxx_messageInfo_CommandResponse.Size(m)
}
func (m *CommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommandResponse proto.InternalMessageInfo

func (m *CommandResponse) GetCmdHead() *MessageHead {
	if m != nil {
		return m.CmdHead
	}
	return nil
}

func (m *CommandResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CommandResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CommandResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CommandResponse) GetInSecureData() []byte {
	if m != nil {
		return m.InSecureData
	}
	return nil
}

func (m *CommandResponse) GetInSecureInfo() string {
	if m != nil {
		return m.InSecureInfo
	}
	return ""
}

// seq msg
type SeqMessage struct {
	Seq                  int32    `protobuf:"varint,10,opt,name=Seq,proto3" json:"Seq,omitempty"`
	MsgTime              int64    `protobuf:"varint,20,opt,name=MsgTime,proto3" json:"MsgTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeqMessage) Reset()         { *m = SeqMessage{} }
func (m *SeqMessage) String() string { return proto.CompactTextString(m) }
func (*SeqMessage) ProtoMessage()    {}
func (*SeqMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d005cd91a5b498e7, []int{8}
}

func (m *SeqMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeqMessage.Unmarshal(m, b)
}
func (m *SeqMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeqMessage.Marshal(b, m, deterministic)
}
func (m *SeqMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeqMessage.Merge(m, src)
}
func (m *SeqMessage) XXX_Size() int {
	return xxx_messageInfo_SeqMessage.Size(m)
}
func (m *SeqMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SeqMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SeqMessage proto.InternalMessageInfo

func (m *SeqMessage) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *SeqMessage) GetMsgTime() int64 {
	if m != nil {
		return m.MsgTime
	}
	return 0
}

// ack msg
type AckMessage struct {
	Ack                  int32    `protobuf:"varint,10,opt,name=Ack,proto3" json:"Ack,omitempty"`
	MsgTime              int64    `protobuf:"varint,20,opt,name=MsgTime,proto3" json:"MsgTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckMessage) Reset()         { *m = AckMessage{} }
func (m *AckMessage) String() string { return proto.CompactTextString(m) }
func (*AckMessage) ProtoMessage()    {}
func (*AckMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d005cd91a5b498e7, []int{9}
}

func (m *AckMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckMessage.Unmarshal(m, b)
}
func (m *AckMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckMessage.Marshal(b, m, deterministic)
}
func (m *AckMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckMessage.Merge(m, src)
}
func (m *AckMessage) XXX_Size() int {
	return xxx_messageInfo_AckMessage.Size(m)
}
func (m *AckMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AckMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AckMessage proto.InternalMessageInfo

func (m *AckMessage) GetAck() int32 {
	if m != nil {
		return m.Ack
	}
	return 0
}

func (m *AckMessage) GetMsgTime() int64 {
	if m != nil {
		return m.MsgTime
	}
	return 0
}

func init() {
	proto.RegisterType((*TestAny)(nil), "edgemsg.TestAny")
	proto.RegisterType((*MessageHead)(nil), "edgemsg.MessageHead")
	proto.RegisterMapType((map[string]string)(nil), "edgemsg.MessageHead.ExtendEntry")
	proto.RegisterType((*ListCmdRequest)(nil), "edgemsg.ListCmdRequest")
	proto.RegisterType((*Command)(nil), "edgemsg.Command")
	proto.RegisterType((*Service)(nil), "edgemsg.Service")
	proto.RegisterType((*ListCmdResponse)(nil), "edgemsg.ListCmdResponse")
	proto.RegisterType((*CommandRequest)(nil), "edgemsg.CommandRequest")
	proto.RegisterType((*CommandResponse)(nil), "edgemsg.CommandResponse")
	proto.RegisterType((*SeqMessage)(nil), "edgemsg.SeqMessage")
	proto.RegisterType((*AckMessage)(nil), "edgemsg.AckMessage")
}

func init() { proto.RegisterFile("commandMsg.proto", fileDescriptor_d005cd91a5b498e7) }

var fileDescriptor_d005cd91a5b498e7 = []byte{
	// 653 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x96, 0xf3, 0xa7, 0x6e, 0x26, 0x55, 0x1b, 0xad, 0x72, 0xd8, 0x5f, 0xf5, 0x53, 0x15, 0x59,
	0x1c, 0x72, 0x40, 0xae, 0x14, 0x2e, 0x05, 0x7a, 0x20, 0xa4, 0x05, 0x2c, 0x35, 0x55, 0xb5, 0xa9,
	0x38, 0x70, 0x73, 0xbd, 0x53, 0xcb, 0x4a, 0xbc, 0xdb, 0x7a, 0xed, 0x88, 0xbc, 0x01, 0x6f, 0xc0,
	0x95, 0x17, 0xe0, 0x49, 0x78, 0x05, 0x1e, 0x06, 0xed, 0x7a, 0xed, 0x3a, 0x15, 0x1c, 0x28, 0xb7,
	0x99, 0x6f, 0x66, 0x67, 0xe6, 0xfb, 0xc6, 0x1e, 0x18, 0x44, 0x32, 0x4d, 0x43, 0xc1, 0xe7, 0x2a,
	0xf6, 0xef, 0x32, 0x99, 0x4b, 0xe2, 0x22, 0x8f, 0x31, 0x55, 0xf1, 0xe1, 0x7f, 0xb1, 0x94, 0xf1,
	0x0a, 0x8f, 0x0d, 0x7c, 0x53, 0xdc, 0x1e, 0x87, 0x62, 0x53, 0xe6, 0x78, 0xef, 0xc1, 0xbd, 0x46,
	0x95, 0x4f, 0xc5, 0x86, 0x10, 0xe8, 0x44, 0x92, 0x23, 0x75, 0x46, 0xce, 0xb8, 0xcb, 0x8c, 0x4d,
	0xc6, 0xd0, 0xe1, 0x61, 0x1e, 0xd2, 0xd6, 0xc8, 0x19, 0xf7, 0x27, 0x43, 0xbf, 0x2c, 0xe4, 0x57,
	0x85, 0xfc, 0xa9, 0xd8, 0x30, 0x93, 0xe1, 0x7d, 0x6b, 0x41, 0x7f, 0x8e, 0x4a, 0x85, 0x31, 0x7e,
	0xc0, 0x90, 0x93, 0x7d, 0x68, 0x05, 0xdc, 0xd4, 0xea, 0xb1, 0x56, 0xc0, 0xc9, 0x21, 0xec, 0xce,
	0x55, 0x7c, 0xbd, 0xb9, 0x43, 0x65, 0xaa, 0x75, 0x59, 0xed, 0x13, 0x0a, 0xae, 0xb6, 0x93, 0x14,
	0x69, 0x7b, 0xe4, 0x8c, 0xdb, 0xac, 0x72, 0xc9, 0x08, 0xfa, 0x73, 0x15, 0x5f, 0x24, 0x6b, 0x34,
	0xd1, 0x8e, 0x89, 0x36, 0x21, 0x9d, 0x31, 0x0b, 0x57, 0x2b, 0x6d, 0xcb, 0x22, 0xa7, 0x5d, 0x53,
	0xba, 0x09, 0x69, 0x5e, 0x8b, 0x24, 0x16, 0x74, 0xc7, 0xcc, 0x62, 0x6c, 0x72, 0x02, 0x3b, 0xe7,
	0x9f, 0x73, 0x14, 0x9c, 0xba, 0xa3, 0xf6, 0xb8, 0x3f, 0x19, 0xf9, 0x56, 0x2b, 0xbf, 0xc1, 0xc1,
	0x2f, 0x53, 0xce, 0x45, 0x9e, 0x6d, 0x98, 0xcd, 0x3f, 0x7c, 0x09, 0xfd, 0x06, 0x4c, 0x06, 0xd0,
	0x5e, 0xe2, 0xc6, 0xf2, 0xd4, 0x26, 0x19, 0x42, 0x77, 0x1d, 0xae, 0x0a, 0x34, 0x2c, 0x7b, 0xac,
	0x74, 0x5e, 0xb5, 0x4e, 0x1c, 0xef, 0x0d, 0xec, 0x5f, 0x24, 0x2a, 0x9f, 0xa5, 0x9c, 0xe1, 0x7d,
	0x81, 0x2a, 0x27, 0x3e, 0xb8, 0xb3, 0x94, 0xeb, 0x5e, 0x14, 0xac, 0xc2, 0xbf, 0x99, 0x83, 0x55,
	0x49, 0xde, 0x57, 0x07, 0xdc, 0x59, 0xb9, 0x66, 0x72, 0x04, 0xf0, 0xae, 0x10, 0x51, 0x9e, 0x48,
	0x11, 0x9c, 0x99, 0xe7, 0x3d, 0xd6, 0x40, 0x34, 0xed, 0xcb, 0x30, 0x45, 0x3a, 0x2c, 0x69, 0x6b,
	0x9b, 0xfc, 0x0f, 0xbd, 0x40, 0xe4, 0x99, 0xe4, 0x45, 0x84, 0xf4, 0xc8, 0x04, 0x1e, 0x00, 0xbd,
	0xa2, 0x69, 0x16, 0xab, 0x40, 0xdc, 0x4a, 0x3a, 0x36, 0xc1, 0xda, 0xd7, 0xdd, 0x18, 0xe6, 0x45,
	0x26, 0x4c, 0x74, 0x52, 0x76, 0x7b, 0x40, 0xbc, 0xef, 0x0e, 0xb8, 0x0b, 0xcc, 0xd6, 0x49, 0x84,
	0x5a, 0x81, 0x45, 0xb6, 0x0e, 0xb8, 0x1d, 0xaa, 0x74, 0x9e, 0x30, 0x0f, 0x05, 0xf7, 0x23, 0x66,
	0x2a, 0x91, 0xc2, 0x8e, 0x53, 0xb9, 0x7a, 0xd2, 0x4b, 0xc9, 0xb1, 0x31, 0x4b, 0xed, 0x93, 0x67,
	0xd0, 0x99, 0xa5, 0x5c, 0xd1, 0x53, 0xb3, 0xd8, 0x41, 0x2d, 0xa8, 0xd5, 0x8d, 0x99, 0xa8, 0x27,
	0xe1, 0xa0, 0xde, 0x85, 0xba, 0x93, 0x42, 0xe1, 0xdf, 0x2e, 0x83, 0x3c, 0x87, 0x5d, 0xcb, 0x58,
	0xd1, 0xe1, 0xa3, 0x66, 0x36, 0xc0, 0xea, 0x0c, 0xef, 0xa7, 0x03, 0xfb, 0xd5, 0x08, 0x4f, 0xdb,
	0xbe, 0x56, 0xcb, 0x96, 0x0b, 0xb8, 0x95, 0xf1, 0x01, 0xd8, 0xfa, 0x1e, 0xb8, 0x15, 0xb3, 0x81,
	0xe8, 0xad, 0x5c, 0x85, 0x59, 0x98, 0x1a, 0x2d, 0xf7, 0x58, 0xe9, 0x10, 0x0f, 0xf6, 0x02, 0xb1,
	0xc0, 0xa8, 0xc8, 0xf0, 0x4c, 0xff, 0xe8, 0x13, 0x13, 0xdc, 0xc2, 0x9a, 0x39, 0x46, 0xf1, 0x53,
	0x53, 0x7b, 0x0b, 0xf3, 0x7e, 0x38, 0x70, 0x50, 0xd3, 0x7b, 0xa2, 0xa0, 0x04, 0x3a, 0x33, 0x7d,
	0x80, 0x86, 0xe5, 0x01, 0xd2, 0xb6, 0x39, 0x0d, 0x65, 0xae, 0xa5, 0x54, 0xb9, 0x3a, 0xdb, 0x4c,
	0x5c, 0xd2, 0xe9, 0x3c, 0x9e, 0xf4, 0x9f, 0xd8, 0x9c, 0x00, 0x2c, 0xf0, 0xbe, 0xea, 0x34, 0x80,
	0xf6, 0x02, 0xef, 0x0d, 0x87, 0x2e, 0xd3, 0x66, 0xf3, 0x60, 0x0d, 0xb7, 0x0e, 0x96, 0x7e, 0x39,
	0x8d, 0x96, 0x8d, 0x97, 0xd3, 0x68, 0x59, 0xbd, 0x9c, 0x46, 0xcb, 0x3f, 0xbf, 0x7c, 0x3b, 0xb8,
	0x72, 0x3e, 0xf5, 0xfc, 0xd7, 0x56, 0xa1, 0x2f, 0x8e, 0x73, 0xb3, 0x63, 0xce, 0xec, 0x8b, 0x5f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xaa, 0xed, 0xb7, 0xda, 0x05, 0x00, 0x00,
}
