// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.0
// source: commandService.proto

package pbgocmd

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_commandService_proto protoreflect.FileDescriptor

var file_commandService_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x1a,
	0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x32, 0xcc, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e,
	0x12, 0x13, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e, 0x53, 0x65, 0x71, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e,
	0x41, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0b,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x17, 0x2e, 0x70, 0x62,
	0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3e, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x17, 0x2e, 0x70, 0x62,
	0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x32, 0x98, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x54, 0x65, 0x73,
	0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e,
	0x53, 0x65, 0x71, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x67,
	0x6f, 0x63, 0x6d, 0x64, 0x2e, 0x41, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x00, 0x12, 0x48, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x44, 0x75, 0x70, 0x6c,
	0x65, 0x78, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62,
	0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x23, 0x0a, 0x11, 0x74,
	0x6f, 0x70, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x78, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x50, 0x01, 0x5a, 0x09, 0x2e, 0x3b, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x88, 0x01, 0x01,
	0x50, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_commandService_proto_goTypes = []interface{}{
	(*SeqMessage)(nil),      // 0: pbgocmd.SeqMessage
	(*ListCmdRequest)(nil),  // 1: pbgocmd.ListCmdRequest
	(*CommandRequest)(nil),  // 2: pbgocmd.CommandRequest
	(*AckMessage)(nil),      // 3: pbgocmd.AckMessage
	(*ListCmdResponse)(nil), // 4: pbgocmd.ListCmdResponse
	(*CommandResponse)(nil), // 5: pbgocmd.CommandResponse
}
var file_commandService_proto_depIdxs = []int32{
	0, // 0: pbgocmd.CommandService.TestConn:input_type -> pbgocmd.SeqMessage
	1, // 1: pbgocmd.CommandService.ListCommand:input_type -> pbgocmd.ListCmdRequest
	2, // 2: pbgocmd.CommandService.Command:input_type -> pbgocmd.CommandRequest
	0, // 3: pbgocmd.CommandStreamService.TestConn:input_type -> pbgocmd.SeqMessage
	2, // 4: pbgocmd.CommandStreamService.CommandDuplex:input_type -> pbgocmd.CommandRequest
	3, // 5: pbgocmd.CommandService.TestConn:output_type -> pbgocmd.AckMessage
	4, // 6: pbgocmd.CommandService.ListCommand:output_type -> pbgocmd.ListCmdResponse
	5, // 7: pbgocmd.CommandService.Command:output_type -> pbgocmd.CommandResponse
	3, // 8: pbgocmd.CommandStreamService.TestConn:output_type -> pbgocmd.AckMessage
	5, // 9: pbgocmd.CommandStreamService.CommandDuplex:output_type -> pbgocmd.CommandResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commandService_proto_init() }
func file_commandService_proto_init() {
	if File_commandService_proto != nil {
		return
	}
	file_commandMsg_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_commandService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_commandService_proto_goTypes,
		DependencyIndexes: file_commandService_proto_depIdxs,
	}.Build()
	File_commandService_proto = out.File
	file_commandService_proto_rawDesc = nil
	file_commandService_proto_goTypes = nil
	file_commandService_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CommandServiceClient is the client API for CommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommandServiceClient interface {
	// 链接测试, 发送一个int类型随机数,服务端+1 后返回.
	TestConn(ctx context.Context, in *SeqMessage, opts ...grpc.CallOption) (*AckMessage, error)
	//
	ListCommand(ctx context.Context, in *ListCmdRequest, opts ...grpc.CallOption) (*ListCmdResponse, error)
	// 发送一次单向命令
	Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
}

type commandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandServiceClient(cc grpc.ClientConnInterface) CommandServiceClient {
	return &commandServiceClient{cc}
}

func (c *commandServiceClient) TestConn(ctx context.Context, in *SeqMessage, opts ...grpc.CallOption) (*AckMessage, error) {
	out := new(AckMessage)
	err := c.cc.Invoke(ctx, "/pbgocmd.CommandService/TestConn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) ListCommand(ctx context.Context, in *ListCmdRequest, opts ...grpc.CallOption) (*ListCmdResponse, error) {
	out := new(ListCmdResponse)
	err := c.cc.Invoke(ctx, "/pbgocmd.CommandService/ListCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, "/pbgocmd.CommandService/Command", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandServiceServer is the server API for CommandService service.
type CommandServiceServer interface {
	// 链接测试, 发送一个int类型随机数,服务端+1 后返回.
	TestConn(context.Context, *SeqMessage) (*AckMessage, error)
	//
	ListCommand(context.Context, *ListCmdRequest) (*ListCmdResponse, error)
	// 发送一次单向命令
	Command(context.Context, *CommandRequest) (*CommandResponse, error)
}

// UnimplementedCommandServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommandServiceServer struct {
}

func (*UnimplementedCommandServiceServer) TestConn(context.Context, *SeqMessage) (*AckMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestConn not implemented")
}
func (*UnimplementedCommandServiceServer) ListCommand(context.Context, *ListCmdRequest) (*ListCmdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCommand not implemented")
}
func (*UnimplementedCommandServiceServer) Command(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Command not implemented")
}

func RegisterCommandServiceServer(s *grpc.Server, srv CommandServiceServer) {
	s.RegisterService(&_CommandService_serviceDesc, srv)
}

func _CommandService_TestConn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).TestConn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbgocmd.CommandService/TestConn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).TestConn(ctx, req.(*SeqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_ListCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCmdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).ListCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbgocmd.CommandService/ListCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).ListCommand(ctx, req.(*ListCmdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_Command_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).Command(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbgocmd.CommandService/Command",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).Command(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbgocmd.CommandService",
	HandlerType: (*CommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestConn",
			Handler:    _CommandService_TestConn_Handler,
		},
		{
			MethodName: "ListCommand",
			Handler:    _CommandService_ListCommand_Handler,
		},
		{
			MethodName: "Command",
			Handler:    _CommandService_Command_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commandService.proto",
}

// CommandStreamServiceClient is the client API for CommandStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommandStreamServiceClient interface {
	// 链接测试, 发送一个int类型随机数,服务端+1 后返回.
	TestConn(ctx context.Context, in *SeqMessage, opts ...grpc.CallOption) (*AckMessage, error)
	// 进行长链接双向通讯命令
	CommandDuplex(ctx context.Context, opts ...grpc.CallOption) (CommandStreamService_CommandDuplexClient, error)
}

type commandStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandStreamServiceClient(cc grpc.ClientConnInterface) CommandStreamServiceClient {
	return &commandStreamServiceClient{cc}
}

func (c *commandStreamServiceClient) TestConn(ctx context.Context, in *SeqMessage, opts ...grpc.CallOption) (*AckMessage, error) {
	out := new(AckMessage)
	err := c.cc.Invoke(ctx, "/pbgocmd.CommandStreamService/TestConn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandStreamServiceClient) CommandDuplex(ctx context.Context, opts ...grpc.CallOption) (CommandStreamService_CommandDuplexClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CommandStreamService_serviceDesc.Streams[0], "/pbgocmd.CommandStreamService/CommandDuplex", opts...)
	if err != nil {
		return nil, err
	}
	x := &commandStreamServiceCommandDuplexClient{stream}
	return x, nil
}

type CommandStreamService_CommandDuplexClient interface {
	Send(*CommandRequest) error
	Recv() (*CommandResponse, error)
	grpc.ClientStream
}

type commandStreamServiceCommandDuplexClient struct {
	grpc.ClientStream
}

func (x *commandStreamServiceCommandDuplexClient) Send(m *CommandRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *commandStreamServiceCommandDuplexClient) Recv() (*CommandResponse, error) {
	m := new(CommandResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CommandStreamServiceServer is the server API for CommandStreamService service.
type CommandStreamServiceServer interface {
	// 链接测试, 发送一个int类型随机数,服务端+1 后返回.
	TestConn(context.Context, *SeqMessage) (*AckMessage, error)
	// 进行长链接双向通讯命令
	CommandDuplex(CommandStreamService_CommandDuplexServer) error
}

// UnimplementedCommandStreamServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommandStreamServiceServer struct {
}

func (*UnimplementedCommandStreamServiceServer) TestConn(context.Context, *SeqMessage) (*AckMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestConn not implemented")
}
func (*UnimplementedCommandStreamServiceServer) CommandDuplex(CommandStreamService_CommandDuplexServer) error {
	return status.Errorf(codes.Unimplemented, "method CommandDuplex not implemented")
}

func RegisterCommandStreamServiceServer(s *grpc.Server, srv CommandStreamServiceServer) {
	s.RegisterService(&_CommandStreamService_serviceDesc, srv)
}

func _CommandStreamService_TestConn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandStreamServiceServer).TestConn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbgocmd.CommandStreamService/TestConn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandStreamServiceServer).TestConn(ctx, req.(*SeqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandStreamService_CommandDuplex_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommandStreamServiceServer).CommandDuplex(&commandStreamServiceCommandDuplexServer{stream})
}

type CommandStreamService_CommandDuplexServer interface {
	Send(*CommandResponse) error
	Recv() (*CommandRequest, error)
	grpc.ServerStream
}

type commandStreamServiceCommandDuplexServer struct {
	grpc.ServerStream
}

func (x *commandStreamServiceCommandDuplexServer) Send(m *CommandResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *commandStreamServiceCommandDuplexServer) Recv() (*CommandRequest, error) {
	m := new(CommandRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CommandStreamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbgocmd.CommandStreamService",
	HandlerType: (*CommandStreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestConn",
			Handler:    _CommandStreamService_TestConn_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CommandDuplex",
			Handler:       _CommandStreamService_CommandDuplex_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "commandService.proto",
}
