// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.0
// source: commandMsg.proto

package pbgocmd

import (
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TestAny struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data *any.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TestAny) Reset() {
	*x = TestAny{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commandMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestAny) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAny) ProtoMessage() {}

func (x *TestAny) ProtoReflect() protoreflect.Message {
	mi := &file_commandMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAny.ProtoReflect.Descriptor instead.
func (*TestAny) Descriptor() ([]byte, []int) {
	return file_commandMsg_proto_rawDescGZIP(), []int{0}
}

func (x *TestAny) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TestAny) GetData() *any.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

// 通用消息头
type MessageHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 消息id
	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// 自定义消息类型
	MsgTypes int32 `protobuf:"varint,2,opt,name=MsgTypes,proto3" json:"MsgTypes,omitempty"`
	// 消息时间, 标准unix时间戳,基于秒单位
	MsgTime int64 `protobuf:"varint,3,opt,name=MsgTime,proto3" json:"MsgTime,omitempty"`
	// 消息有效时间,单位: 毫秒,为0则表示不限制,在两台主机时间与ntp服务器同步一致的情况,
	MsgLiveTime int64 `protobuf:"varint,4,opt,name=MsgLiveTime,proto3" json:"MsgLiveTime,omitempty"`
	// 调用超时时间,单位: 毫秒,为0则表示不限制,如果消息在多个节点进行转发调用时,该字段为每个节点转发调用的所允许的最大超时时长
	CallTimeout int32 `protobuf:"varint,5,opt,name=CallTimeout,proto3" json:"CallTimeout,omitempty"`
	// Extend字段,数据签名
	Sign string `protobuf:"bytes,6,opt,name=Sign,proto3" json:"Sign,omitempty"`
	// 额外控制扩展消息头, 如是否加密, 加密类型,各种id,等信息.
	Extend map[string]string `protobuf:"bytes,7,rep,name=Extend,proto3" json:"Extend,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MessageHead) Reset() {
	*x = MessageHead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commandMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHead) ProtoMessage() {}

func (x *MessageHead) ProtoReflect() protoreflect.Message {
	mi := &file_commandMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHead.ProtoReflect.Descriptor instead.
func (*MessageHead) Descriptor() ([]byte, []int) {
	return file_commandMsg_proto_rawDescGZIP(), []int{1}
}

func (x *MessageHead) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageHead) GetMsgTypes() int32 {
	if x != nil {
		return x.MsgTypes
	}
	return 0
}

func (x *MessageHead) GetMsgTime() int64 {
	if x != nil {
		return x.MsgTime
	}
	return 0
}

func (x *MessageHead) GetMsgLiveTime() int64 {
	if x != nil {
		return x.MsgLiveTime
	}
	return 0
}

func (x *MessageHead) GetCallTimeout() int32 {
	if x != nil {
		return x.CallTimeout
	}
	return 0
}

func (x *MessageHead) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *MessageHead) GetExtend() map[string]string {
	if x != nil {
		return x.Extend
	}
	return nil
}

// 命令列表请求
type ListCmdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CmdHead *MessageHead `protobuf:"bytes,10,opt,name=CmdHead,proto3" json:"CmdHead,omitempty"`
}

func (x *ListCmdRequest) Reset() {
	*x = ListCmdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commandMsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCmdRequest) ProtoMessage() {}

func (x *ListCmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commandMsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCmdRequest.ProtoReflect.Descriptor instead.
func (*ListCmdRequest) Descriptor() ([]byte, []int) {
	return file_commandMsg_proto_rawDescGZIP(), []int{2}
}

func (x *ListCmdRequest) GetCmdHead() *MessageHead {
	if x != nil {
		return x.CmdHead
	}
	return nil
}

// 命令结构对象
type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FunctionID string `protobuf:"bytes,10,opt,name=FunctionID,proto3" json:"FunctionID,omitempty"`
	Name       string `protobuf:"bytes,20,opt,name=Name,proto3" json:"Name,omitempty"`
	Introduce  string `protobuf:"bytes,30,opt,name=Introduce,proto3" json:"Introduce,omitempty"`
	ArgsInfo   string `protobuf:"bytes,40,opt,name=ArgsInfo,proto3" json:"ArgsInfo,omitempty"`
	ReturnInfo string `protobuf:"bytes,50,opt,name=ReturnInfo,proto3" json:"ReturnInfo,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commandMsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_commandMsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_commandMsg_proto_rawDescGZIP(), []int{3}
}

func (x *Command) GetFunctionID() string {
	if x != nil {
		return x.FunctionID
	}
	return ""
}

func (x *Command) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Command) GetIntroduce() string {
	if x != nil {
		return x.Introduce
	}
	return ""
}

func (x *Command) GetArgsInfo() string {
	if x != nil {
		return x.ArgsInfo
	}
	return ""
}

func (x *Command) GetReturnInfo() string {
	if x != nil {
		return x.ReturnInfo
	}
	return ""
}

type Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrvId     string     `protobuf:"bytes,10,opt,name=SrvId,proto3" json:"SrvId,omitempty"`
	Name      string     `protobuf:"bytes,20,opt,name=Name,proto3" json:"Name,omitempty"`
	Introduce string     `protobuf:"bytes,30,opt,name=Introduce,proto3" json:"Introduce,omitempty"`
	Version   string     `protobuf:"bytes,40,opt,name=Version,proto3" json:"Version,omitempty"`
	NodeInfo  string     `protobuf:"bytes,50,opt,name=NodeInfo,proto3" json:"NodeInfo,omitempty"`
	Cmds      []*Command `protobuf:"bytes,60,rep,name=Cmds,proto3" json:"Cmds,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commandMsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_commandMsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_commandMsg_proto_rawDescGZIP(), []int{4}
}

func (x *Service) GetSrvId() string {
	if x != nil {
		return x.SrvId
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetIntroduce() string {
	if x != nil {
		return x.Introduce
	}
	return ""
}

func (x *Service) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Service) GetNodeInfo() string {
	if x != nil {
		return x.NodeInfo
	}
	return ""
}

func (x *Service) GetCmds() []*Command {
	if x != nil {
		return x.Cmds
	}
	return nil
}

// 命令列表响应体
type ListCmdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CmdHead  *MessageHead `protobuf:"bytes,10,opt,name=CmdHead,proto3" json:"CmdHead,omitempty"`
	Services []*Service   `protobuf:"bytes,20,rep,name=Services,proto3" json:"Services,omitempty"`
}

func (x *ListCmdResponse) Reset() {
	*x = ListCmdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commandMsg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCmdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCmdResponse) ProtoMessage() {}

func (x *ListCmdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commandMsg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCmdResponse.ProtoReflect.Descriptor instead.
func (*ListCmdResponse) Descriptor() ([]byte, []int) {
	return file_commandMsg_proto_rawDescGZIP(), []int{5}
}

func (x *ListCmdResponse) GetCmdHead() *MessageHead {
	if x != nil {
		return x.CmdHead
	}
	return nil
}

func (x *ListCmdResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

// 命令消息
type CommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 通用消息头,多个message共用.
	CmdHead *MessageHead `protobuf:"bytes,10,opt,name=CmdHead,proto3" json:"CmdHead,omitempty"`
	// 分开传输
	ServiceId    string `protobuf:"bytes,20,opt,name=ServiceId,proto3" json:"ServiceId,omitempty"`
	FunctionId   string `protobuf:"bytes,30,opt,name=FunctionId,proto3" json:"FunctionId,omitempty"`
	Param        []byte `protobuf:"bytes,40,opt,name=Param,proto3" json:"Param,omitempty"`               // 请求参数
	InSecureData []byte `protobuf:"bytes,50,opt,name=InSecureData,proto3" json:"InSecureData,omitempty"` // 未加密的大结构数据包
	InSecureInfo string `protobuf:"bytes,60,opt,name=InSecureInfo,proto3" json:"InSecureInfo,omitempty"` // 未加密的大结构数据包,扩展描述信息
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commandMsg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commandMsg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_commandMsg_proto_rawDescGZIP(), []int{6}
}

func (x *CommandRequest) GetCmdHead() *MessageHead {
	if x != nil {
		return x.CmdHead
	}
	return nil
}

func (x *CommandRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *CommandRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *CommandRequest) GetParam() []byte {
	if x != nil {
		return x.Param
	}
	return nil
}

func (x *CommandRequest) GetInSecureData() []byte {
	if x != nil {
		return x.InSecureData
	}
	return nil
}

func (x *CommandRequest) GetInSecureInfo() string {
	if x != nil {
		return x.InSecureInfo
	}
	return ""
}

// 命令结果
type CommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 通用消息头,多个message共用.
	CmdHead      *MessageHead `protobuf:"bytes,10,opt,name=CmdHead,proto3" json:"CmdHead,omitempty"`
	Code         int32        `protobuf:"varint,20,opt,name=Code,proto3" json:"Code,omitempty"`
	Message      string       `protobuf:"bytes,30,opt,name=Message,proto3" json:"Message,omitempty"`
	Data         []byte       `protobuf:"bytes,40,opt,name=Data,proto3" json:"Data,omitempty"`
	InSecureData []byte       `protobuf:"bytes,50,opt,name=InSecureData,proto3" json:"InSecureData,omitempty"`
	InSecureInfo string       `protobuf:"bytes,60,opt,name=InSecureInfo,proto3" json:"InSecureInfo,omitempty"` // 未加密的大结构数据包,扩展描述信息
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commandMsg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commandMsg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_commandMsg_proto_rawDescGZIP(), []int{7}
}

func (x *CommandResponse) GetCmdHead() *MessageHead {
	if x != nil {
		return x.CmdHead
	}
	return nil
}

func (x *CommandResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommandResponse) GetInSecureData() []byte {
	if x != nil {
		return x.InSecureData
	}
	return nil
}

func (x *CommandResponse) GetInSecureInfo() string {
	if x != nil {
		return x.InSecureInfo
	}
	return ""
}

// seq msg
type SeqMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq     int32 `protobuf:"varint,10,opt,name=Seq,proto3" json:"Seq,omitempty"`
	MsgTime int64 `protobuf:"varint,20,opt,name=MsgTime,proto3" json:"MsgTime,omitempty"` // 标准unix时间戳,基于秒单位
}

func (x *SeqMessage) Reset() {
	*x = SeqMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commandMsg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeqMessage) ProtoMessage() {}

func (x *SeqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_commandMsg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeqMessage.ProtoReflect.Descriptor instead.
func (*SeqMessage) Descriptor() ([]byte, []int) {
	return file_commandMsg_proto_rawDescGZIP(), []int{8}
}

func (x *SeqMessage) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SeqMessage) GetMsgTime() int64 {
	if x != nil {
		return x.MsgTime
	}
	return 0
}

// ack msg
type AckMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack     int32 `protobuf:"varint,10,opt,name=Ack,proto3" json:"Ack,omitempty"`
	MsgTime int64 `protobuf:"varint,20,opt,name=MsgTime,proto3" json:"MsgTime,omitempty"` // 标准unix时间戳,基于秒单位
}

func (x *AckMessage) Reset() {
	*x = AckMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commandMsg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessage) ProtoMessage() {}

func (x *AckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_commandMsg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessage.ProtoReflect.Descriptor instead.
func (*AckMessage) Descriptor() ([]byte, []int) {
	return file_commandMsg_proto_rawDescGZIP(), []int{9}
}

func (x *AckMessage) GetAck() int32 {
	if x != nil {
		return x.Ack
	}
	return 0
}

func (x *AckMessage) GetMsgTime() int64 {
	if x != nil {
		return x.MsgTime
	}
	return 0
}

var File_commandMsg_proto protoreflect.FileDescriptor

var file_commandMsg_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x1a, 0x19, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x07, 0x54, 0x65, 0x73, 0x74, 0x41, 0x6e,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0xa0, 0x02, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d,
	0x73, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4d, 0x73,
	0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x76, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x4d, 0x73, 0x67, 0x4c,
	0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x54,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x43, 0x61,
	0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x67,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x38, 0x0a,
	0x06, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x06, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x1a, 0x39, 0x0a, 0x0b, 0x45, 0x78, 0x74, 0x65, 0x6e,
	0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x40, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x43, 0x6d, 0x64, 0x48, 0x65, 0x61, 0x64, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x52, 0x07, 0x43, 0x6d, 0x64,
	0x48, 0x65, 0x61, 0x64, 0x22, 0x97, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x65, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x72, 0x67, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x28,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x41, 0x72, 0x67, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e,
	0x0a, 0x0a, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x32, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xad,
	0x01, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x72,
	0x76, 0x49, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x72, 0x76, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x65, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x28, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x32, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a, 0x04, 0x43, 0x6d, 0x64, 0x73,
	0x18, 0x3c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x04, 0x43, 0x6d, 0x64, 0x73, 0x22, 0x6f,
	0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2e, 0x0a, 0x07, 0x43, 0x6d, 0x64, 0x48, 0x65, 0x61, 0x64, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x52, 0x07, 0x43, 0x6d, 0x64, 0x48, 0x65, 0x61,
	0x64, 0x12, 0x2c, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x14, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22,
	0xdc, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x43, 0x6d, 0x64, 0x48, 0x65, 0x61, 0x64, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x52, 0x07, 0x43, 0x6d, 0x64, 0x48, 0x65,
	0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18,
	0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x1e,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x22, 0x0a, 0x0c, 0x49, 0x6e, 0x53, 0x65, 0x63, 0x75,
	0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x32, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x49, 0x6e,
	0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x49, 0x6e,
	0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x3c, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x49, 0x6e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xcb,
	0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x43, 0x6d, 0x64, 0x48, 0x65, 0x61, 0x64, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x52, 0x07, 0x43, 0x6d, 0x64, 0x48, 0x65,
	0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x49, 0x6e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x32, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x49, 0x6e, 0x53, 0x65,
	0x63, 0x75, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x49, 0x6e, 0x53, 0x65,
	0x63, 0x75, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x3c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x49, 0x6e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x38, 0x0a, 0x0a,
	0x53, 0x65, 0x71, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65,
	0x71, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x53, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x73, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4d,
	0x73, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x0a, 0x41, 0x63, 0x6b, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x69, 0x6d, 0x65,
	0x42, 0x23, 0x0a, 0x11, 0x74, 0x6f, 0x70, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x78, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x50, 0x01, 0x5a, 0x09, 0x2e, 0x3b, 0x70, 0x62, 0x67, 0x6f, 0x63,
	0x6d, 0x64, 0x88, 0x01, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_commandMsg_proto_rawDescOnce sync.Once
	file_commandMsg_proto_rawDescData = file_commandMsg_proto_rawDesc
)

func file_commandMsg_proto_rawDescGZIP() []byte {
	file_commandMsg_proto_rawDescOnce.Do(func() {
		file_commandMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_commandMsg_proto_rawDescData)
	})
	return file_commandMsg_proto_rawDescData
}

var file_commandMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_commandMsg_proto_goTypes = []interface{}{
	(*TestAny)(nil),         // 0: pbgocmd.TestAny
	(*MessageHead)(nil),     // 1: pbgocmd.MessageHead
	(*ListCmdRequest)(nil),  // 2: pbgocmd.ListCmdRequest
	(*Command)(nil),         // 3: pbgocmd.Command
	(*Service)(nil),         // 4: pbgocmd.Service
	(*ListCmdResponse)(nil), // 5: pbgocmd.ListCmdResponse
	(*CommandRequest)(nil),  // 6: pbgocmd.CommandRequest
	(*CommandResponse)(nil), // 7: pbgocmd.CommandResponse
	(*SeqMessage)(nil),      // 8: pbgocmd.SeqMessage
	(*AckMessage)(nil),      // 9: pbgocmd.AckMessage
	nil,                     // 10: pbgocmd.MessageHead.ExtendEntry
	(*any.Any)(nil),         // 11: google.protobuf.Any
}
var file_commandMsg_proto_depIdxs = []int32{
	11, // 0: pbgocmd.TestAny.data:type_name -> google.protobuf.Any
	10, // 1: pbgocmd.MessageHead.Extend:type_name -> pbgocmd.MessageHead.ExtendEntry
	1,  // 2: pbgocmd.ListCmdRequest.CmdHead:type_name -> pbgocmd.MessageHead
	3,  // 3: pbgocmd.Service.Cmds:type_name -> pbgocmd.Command
	1,  // 4: pbgocmd.ListCmdResponse.CmdHead:type_name -> pbgocmd.MessageHead
	4,  // 5: pbgocmd.ListCmdResponse.Services:type_name -> pbgocmd.Service
	1,  // 6: pbgocmd.CommandRequest.CmdHead:type_name -> pbgocmd.MessageHead
	1,  // 7: pbgocmd.CommandResponse.CmdHead:type_name -> pbgocmd.MessageHead
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_commandMsg_proto_init() }
func file_commandMsg_proto_init() {
	if File_commandMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_commandMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestAny); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commandMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commandMsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCmdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commandMsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commandMsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commandMsg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCmdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commandMsg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commandMsg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commandMsg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeqMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commandMsg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_commandMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commandMsg_proto_goTypes,
		DependencyIndexes: file_commandMsg_proto_depIdxs,
		MessageInfos:      file_commandMsg_proto_msgTypes,
	}.Build()
	File_commandMsg_proto = out.File
	file_commandMsg_proto_rawDesc = nil
	file_commandMsg_proto_goTypes = nil
	file_commandMsg_proto_depIdxs = nil
}
