// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.0
// source: edgeServer.proto

package pbgocmd

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_struct "github.com/golang/protobuf/ptypes/struct"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Symbols defined in public import of google/protobuf/struct.proto.

type NullValue = _struct.NullValue

const NullValue_NULL_VALUE = _struct.NullValue_NULL_VALUE

var NullValue_name = _struct.NullValue_name
var NullValue_value = _struct.NullValue_value

type Struct = _struct.Struct
type Value = _struct.Value
type Value_NullValue = _struct.Value_NullValue
type Value_NumberValue = _struct.Value_NumberValue
type Value_StringValue = _struct.Value_StringValue
type Value_BoolValue = _struct.Value_BoolValue
type Value_StructValue = _struct.Value_StructValue
type Value_ListValue = _struct.Value_ListValue
type ListValue = _struct.ListValue

// Symbols defined in public import of google/protobuf/any.proto.

type Any = any.Any

type GateWayType int32

const (
	GateWayType_Unknow               GateWayType = 0
	GateWayType_MqttGateWay          GateWayType = 1
	GateWayType_MqttWebsocketGateWay GateWayType = 2
	GateWayType_GrpcGateWay          GateWayType = 3
	GateWayType_TcpGateWay           GateWayType = 4
)

// Enum value maps for GateWayType.
var (
	GateWayType_name = map[int32]string{
		0: "Unknow",
		1: "MqttGateWay",
		2: "MqttWebsocketGateWay",
		3: "GrpcGateWay",
		4: "TcpGateWay",
	}
	GateWayType_value = map[string]int32{
		"Unknow":               0,
		"MqttGateWay":          1,
		"MqttWebsocketGateWay": 2,
		"GrpcGateWay":          3,
		"TcpGateWay":           4,
	}
)

func (x GateWayType) Enum() *GateWayType {
	p := new(GateWayType)
	*p = x
	return p
}

func (x GateWayType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GateWayType) Descriptor() protoreflect.EnumDescriptor {
	return file_edgeServer_proto_enumTypes[0].Descriptor()
}

func (GateWayType) Type() protoreflect.EnumType {
	return &file_edgeServer_proto_enumTypes[0]
}

func (x GateWayType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GateWayType.Descriptor instead.
func (GateWayType) EnumDescriptor() ([]byte, []int) {
	return file_edgeServer_proto_rawDescGZIP(), []int{0}
}

type NorthProtoMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	//  bytes Data = 3;
	Data *any.Any `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"` //  google.protobuf.Struct Data = 3;
}

func (x *NorthProtoMsg) Reset() {
	*x = NorthProtoMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edgeServer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NorthProtoMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NorthProtoMsg) ProtoMessage() {}

func (x *NorthProtoMsg) ProtoReflect() protoreflect.Message {
	mi := &file_edgeServer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NorthProtoMsg.ProtoReflect.Descriptor instead.
func (*NorthProtoMsg) Descriptor() ([]byte, []int) {
	return file_edgeServer_proto_rawDescGZIP(), []int{0}
}

func (x *NorthProtoMsg) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NorthProtoMsg) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *NorthProtoMsg) GetData() *any.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type TlsConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enable        bool   `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`            // 开启/关闭
	SkipVerify    bool   `protobuf:"varint,3,opt,name=skipVerify,proto3" json:"skipVerify,omitempty"`    // 基础校验
	ServerCaCert  []byte `protobuf:"bytes,4,opt,name=serverCaCert,proto3" json:"serverCaCert,omitempty"` // 服务端ca证书
	ClientCaCert  []byte `protobuf:"bytes,5,opt,name=clientCaCert,proto3" json:"clientCaCert,omitempty"`
	ClientCert    []byte `protobuf:"bytes,6,opt,name=clientCert,proto3" json:"clientCert,omitempty"`       // 客户端证书
	ClientCertKey []byte `protobuf:"bytes,7,opt,name=clientCertKey,proto3" json:"clientCertKey,omitempty"` // 客户端key
}

func (x *TlsConfig) Reset() {
	*x = TlsConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edgeServer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TlsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TlsConfig) ProtoMessage() {}

func (x *TlsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_edgeServer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TlsConfig.ProtoReflect.Descriptor instead.
func (*TlsConfig) Descriptor() ([]byte, []int) {
	return file_edgeServer_proto_rawDescGZIP(), []int{1}
}

func (x *TlsConfig) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *TlsConfig) GetSkipVerify() bool {
	if x != nil {
		return x.SkipVerify
	}
	return false
}

func (x *TlsConfig) GetServerCaCert() []byte {
	if x != nil {
		return x.ServerCaCert
	}
	return nil
}

func (x *TlsConfig) GetClientCaCert() []byte {
	if x != nil {
		return x.ClientCaCert
	}
	return nil
}

func (x *TlsConfig) GetClientCert() []byte {
	if x != nil {
		return x.ClientCert
	}
	return nil
}

func (x *TlsConfig) GetClientCertKey() []byte {
	if x != nil {
		return x.ClientCertKey
	}
	return nil
}

type EdgeMqttServerDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr     string     `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`  // 主机地址
	Port     int32      `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"` // 主机端口
	Username string     `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Passwd   string     `protobuf:"bytes,4,opt,name=passwd,proto3" json:"passwd,omitempty"`
	CliId    string     `protobuf:"bytes,5,opt,name=cliId,proto3" json:"cliId,omitempty"`
	Tls      *TlsConfig `protobuf:"bytes,6,opt,name=tls,proto3" json:"tls,omitempty"` // 证书配置
}

func (x *EdgeMqttServerDto) Reset() {
	*x = EdgeMqttServerDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edgeServer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EdgeMqttServerDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeMqttServerDto) ProtoMessage() {}

func (x *EdgeMqttServerDto) ProtoReflect() protoreflect.Message {
	mi := &file_edgeServer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeMqttServerDto.ProtoReflect.Descriptor instead.
func (*EdgeMqttServerDto) Descriptor() ([]byte, []int) {
	return file_edgeServer_proto_rawDescGZIP(), []int{2}
}

func (x *EdgeMqttServerDto) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *EdgeMqttServerDto) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *EdgeMqttServerDto) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EdgeMqttServerDto) GetPasswd() string {
	if x != nil {
		return x.Passwd
	}
	return ""
}

func (x *EdgeMqttServerDto) GetCliId() string {
	if x != nil {
		return x.CliId
	}
	return ""
}

func (x *EdgeMqttServerDto) GetTls() *TlsConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

type ServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Kind:
	//	*ServerInfo_MqttServer
	Kind isServerInfo_Kind `protobuf_oneof:"kind"`
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edgeServer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_edgeServer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_edgeServer_proto_rawDescGZIP(), []int{3}
}

func (m *ServerInfo) GetKind() isServerInfo_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *ServerInfo) GetMqttServer() *EdgeMqttServerDto {
	if x, ok := x.GetKind().(*ServerInfo_MqttServer); ok {
		return x.MqttServer
	}
	return nil
}

type isServerInfo_Kind interface {
	isServerInfo_Kind()
}

type ServerInfo_MqttServer struct {
	MqttServer *EdgeMqttServerDto `protobuf:"bytes,1,opt,name=mqttServer,proto3,oneof"`
}

func (*ServerInfo_MqttServer) isServerInfo_Kind() {}

//
type EdgeServerDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerType GateWayType `protobuf:"varint,2,opt,name=serverType,proto3,enum=pbgocmd.GateWayType" json:"serverType,omitempty"`
	Enable     bool        `protobuf:"varint,3,opt,name=enable,proto3" json:"enable,omitempty"`
	//  google.protobuf.Struct serverInfo = 4;
	ServerInfo *ServerInfo `protobuf:"bytes,4,opt,name=ServerInfo,proto3" json:"ServerInfo,omitempty"`
}

func (x *EdgeServerDto) Reset() {
	*x = EdgeServerDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edgeServer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EdgeServerDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeServerDto) ProtoMessage() {}

func (x *EdgeServerDto) ProtoReflect() protoreflect.Message {
	mi := &file_edgeServer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeServerDto.ProtoReflect.Descriptor instead.
func (*EdgeServerDto) Descriptor() ([]byte, []int) {
	return file_edgeServer_proto_rawDescGZIP(), []int{4}
}

func (x *EdgeServerDto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EdgeServerDto) GetServerType() GateWayType {
	if x != nil {
		return x.ServerType
	}
	return GateWayType_Unknow
}

func (x *EdgeServerDto) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *EdgeServerDto) GetServerInfo() *ServerInfo {
	if x != nil {
		return x.ServerInfo
	}
	return nil
}

type EdgeGaywayOnlineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EdgeGaywayId  string   `protobuf:"bytes,1,opt,name=edgeGaywayId,proto3" json:"edgeGaywayId,omitempty"`
	DeviceModel   string   `protobuf:"bytes,2,opt,name=deviceModel,proto3" json:"deviceModel,omitempty"`
	HardVersion   string   `protobuf:"bytes,3,opt,name=hardVersion,proto3" json:"hardVersion,omitempty"`
	SoftVersion   string   `protobuf:"bytes,4,opt,name=softVersion,proto3" json:"softVersion,omitempty"`
	TunnelSupport []string `protobuf:"bytes,5,rep,name=tunnelSupport,proto3" json:"tunnelSupport,omitempty"`
	NotBefore     int64    `protobuf:"varint,6,opt,name=notBefore,proto3" json:"notBefore,omitempty"`
	NotAfter      int64    `protobuf:"varint,7,opt,name=notAfter,proto3" json:"notAfter,omitempty"`
}

func (x *EdgeGaywayOnlineReq) Reset() {
	*x = EdgeGaywayOnlineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edgeServer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EdgeGaywayOnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeGaywayOnlineReq) ProtoMessage() {}

func (x *EdgeGaywayOnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_edgeServer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeGaywayOnlineReq.ProtoReflect.Descriptor instead.
func (*EdgeGaywayOnlineReq) Descriptor() ([]byte, []int) {
	return file_edgeServer_proto_rawDescGZIP(), []int{5}
}

func (x *EdgeGaywayOnlineReq) GetEdgeGaywayId() string {
	if x != nil {
		return x.EdgeGaywayId
	}
	return ""
}

func (x *EdgeGaywayOnlineReq) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *EdgeGaywayOnlineReq) GetHardVersion() string {
	if x != nil {
		return x.HardVersion
	}
	return ""
}

func (x *EdgeGaywayOnlineReq) GetSoftVersion() string {
	if x != nil {
		return x.SoftVersion
	}
	return ""
}

func (x *EdgeGaywayOnlineReq) GetTunnelSupport() []string {
	if x != nil {
		return x.TunnelSupport
	}
	return nil
}

func (x *EdgeGaywayOnlineReq) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *EdgeGaywayOnlineReq) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

type EdgeGaywayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EdgeGaywayId string `protobuf:"bytes,1,opt,name=edgeGaywayId,proto3" json:"edgeGaywayId,omitempty"`
	ProjectId    string `protobuf:"bytes,2,opt,name=projectId,proto3" json:"projectId,omitempty"`
}

func (x *EdgeGaywayReq) Reset() {
	*x = EdgeGaywayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edgeServer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EdgeGaywayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeGaywayReq) ProtoMessage() {}

func (x *EdgeGaywayReq) ProtoReflect() protoreflect.Message {
	mi := &file_edgeServer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeGaywayReq.ProtoReflect.Descriptor instead.
func (*EdgeGaywayReq) Descriptor() ([]byte, []int) {
	return file_edgeServer_proto_rawDescGZIP(), []int{6}
}

func (x *EdgeGaywayReq) GetEdgeGaywayId() string {
	if x != nil {
		return x.EdgeGaywayId
	}
	return ""
}

func (x *EdgeGaywayReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

var File_edgeServer_proto protoreflect.FileDescriptor

var file_edgeServer_proto_rawDesc = []byte{
	0x0a, 0x10, 0x65, 0x64, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a, 0x0d, 0x4e, 0x6f, 0x72, 0x74, 0x68, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x22, 0x0a, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0xd1, 0x01,
	0x0a, 0x09, 0x54, 0x6c, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6b, 0x69, 0x70, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x73, 0x6b, 0x69, 0x70, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x61, 0x43,
	0x65, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x43, 0x61, 0x43, 0x65, 0x72, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x43, 0x61, 0x43, 0x65, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x43, 0x65, 0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x65, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x65, 0x72, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x65, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x65, 0x72, 0x74, 0x4b, 0x65,
	0x79, 0x22, 0xab, 0x01, 0x0a, 0x11, 0x45, 0x64, 0x67, 0x65, 0x4d, 0x71, 0x74, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x69, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x63, 0x6c, 0x69, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x03, 0x74, 0x6c, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64,
	0x2e, 0x54, 0x6c, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x03, 0x74, 0x6c, 0x73, 0x22,
	0x52, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3c, 0x0a,
	0x0a, 0x6d, 0x71, 0x74, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e, 0x45, 0x64, 0x67, 0x65,
	0x4d, 0x71, 0x74, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x48, 0x00, 0x52,
	0x0a, 0x6d, 0x71, 0x74, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x22, 0xa2, 0x01, 0x0a, 0x0d, 0x45, 0x64, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x67, 0x6f,
	0x63, 0x6d, 0x64, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x57, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d,
	0x64, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xff, 0x01, 0x0a, 0x13, 0x45, 0x64, 0x67,
	0x65, 0x47, 0x61, 0x79, 0x77, 0x61, 0x79, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x22, 0x0a, 0x0c, 0x65, 0x64, 0x67, 0x65, 0x47, 0x61, 0x79, 0x77, 0x61, 0x79, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x64, 0x67, 0x65, 0x47, 0x61, 0x79, 0x77,
	0x61, 0x79, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x68, 0x61, 0x72, 0x64, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x61, 0x72,
	0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x6f, 0x66, 0x74,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x6f, 0x66, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x75,
	0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0d, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x6e, 0x6f, 0x74, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6e, 0x6f, 0x74, 0x41, 0x66, 0x74, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x6e, 0x6f, 0x74, 0x41, 0x66, 0x74, 0x65, 0x72, 0x22, 0x51, 0x0a, 0x0d, 0x45, 0x64,
	0x67, 0x65, 0x47, 0x61, 0x79, 0x77, 0x61, 0x79, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x65,
	0x64, 0x67, 0x65, 0x47, 0x61, 0x79, 0x77, 0x61, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x65, 0x64, 0x67, 0x65, 0x47, 0x61, 0x79, 0x77, 0x61, 0x79, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x2a, 0x65, 0x0a,
	0x0b, 0x47, 0x61, 0x74, 0x65, 0x57, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06,
	0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x71, 0x74, 0x74,
	0x47, 0x61, 0x74, 0x65, 0x57, 0x61, 0x79, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x4d, 0x71, 0x74,
	0x74, 0x57, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x47, 0x61, 0x74, 0x65, 0x57, 0x61,
	0x79, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x47, 0x72, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65, 0x57,
	0x61, 0x79, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x63, 0x70, 0x47, 0x61, 0x74, 0x65, 0x57,
	0x61, 0x79, 0x10, 0x04, 0x32, 0x5c, 0x0a, 0x0e, 0x45, 0x64, 0x67, 0x65, 0x41, 0x70, 0x69, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0e, 0x67, 0x65, 0x74, 0x4d, 0x71, 0x74,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x63,
	0x6d, 0x64, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x4d, 0x71, 0x74, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x44, 0x74, 0x6f, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e, 0x45,
	0x64, 0x67, 0x65, 0x4d, 0x71, 0x74, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x74, 0x6f,
	0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x50,
	0x00, 0x50, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_edgeServer_proto_rawDescOnce sync.Once
	file_edgeServer_proto_rawDescData = file_edgeServer_proto_rawDesc
)

func file_edgeServer_proto_rawDescGZIP() []byte {
	file_edgeServer_proto_rawDescOnce.Do(func() {
		file_edgeServer_proto_rawDescData = protoimpl.X.CompressGZIP(file_edgeServer_proto_rawDescData)
	})
	return file_edgeServer_proto_rawDescData
}

var file_edgeServer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_edgeServer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_edgeServer_proto_goTypes = []interface{}{
	(GateWayType)(0),            // 0: pbgocmd.GateWayType
	(*NorthProtoMsg)(nil),       // 1: pbgocmd.NorthProtoMsg
	(*TlsConfig)(nil),           // 2: pbgocmd.TlsConfig
	(*EdgeMqttServerDto)(nil),   // 3: pbgocmd.EdgeMqttServerDto
	(*ServerInfo)(nil),          // 4: pbgocmd.ServerInfo
	(*EdgeServerDto)(nil),       // 5: pbgocmd.EdgeServerDto
	(*EdgeGaywayOnlineReq)(nil), // 6: pbgocmd.EdgeGaywayOnlineReq
	(*EdgeGaywayReq)(nil),       // 7: pbgocmd.EdgeGaywayReq
	(*any.Any)(nil),             // 8: google.protobuf.Any
}
var file_edgeServer_proto_depIdxs = []int32{
	8, // 0: pbgocmd.NorthProtoMsg.Data:type_name -> google.protobuf.Any
	2, // 1: pbgocmd.EdgeMqttServerDto.tls:type_name -> pbgocmd.TlsConfig
	3, // 2: pbgocmd.ServerInfo.mqttServer:type_name -> pbgocmd.EdgeMqttServerDto
	0, // 3: pbgocmd.EdgeServerDto.serverType:type_name -> pbgocmd.GateWayType
	4, // 4: pbgocmd.EdgeServerDto.ServerInfo:type_name -> pbgocmd.ServerInfo
	3, // 5: pbgocmd.EdgeApiService.getMqttServers:input_type -> pbgocmd.EdgeMqttServerDto
	3, // 6: pbgocmd.EdgeApiService.getMqttServers:output_type -> pbgocmd.EdgeMqttServerDto
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_edgeServer_proto_init() }
func file_edgeServer_proto_init() {
	if File_edgeServer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_edgeServer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NorthProtoMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edgeServer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TlsConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edgeServer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EdgeMqttServerDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edgeServer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edgeServer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EdgeServerDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edgeServer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EdgeGaywayOnlineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edgeServer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EdgeGaywayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_edgeServer_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ServerInfo_MqttServer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_edgeServer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_edgeServer_proto_goTypes,
		DependencyIndexes: file_edgeServer_proto_depIdxs,
		EnumInfos:         file_edgeServer_proto_enumTypes,
		MessageInfos:      file_edgeServer_proto_msgTypes,
	}.Build()
	File_edgeServer_proto = out.File
	file_edgeServer_proto_rawDesc = nil
	file_edgeServer_proto_goTypes = nil
	file_edgeServer_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EdgeApiServiceClient is the client API for EdgeApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EdgeApiServiceClient interface {
	// 获取mqtt服务器信息
	GetMqttServers(ctx context.Context, in *EdgeMqttServerDto, opts ...grpc.CallOption) (*EdgeMqttServerDto, error)
}

type edgeApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEdgeApiServiceClient(cc grpc.ClientConnInterface) EdgeApiServiceClient {
	return &edgeApiServiceClient{cc}
}

func (c *edgeApiServiceClient) GetMqttServers(ctx context.Context, in *EdgeMqttServerDto, opts ...grpc.CallOption) (*EdgeMqttServerDto, error) {
	out := new(EdgeMqttServerDto)
	err := c.cc.Invoke(ctx, "/pbgocmd.EdgeApiService/getMqttServers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdgeApiServiceServer is the server API for EdgeApiService service.
type EdgeApiServiceServer interface {
	// 获取mqtt服务器信息
	GetMqttServers(context.Context, *EdgeMqttServerDto) (*EdgeMqttServerDto, error)
}

// UnimplementedEdgeApiServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEdgeApiServiceServer struct {
}

func (*UnimplementedEdgeApiServiceServer) GetMqttServers(context.Context, *EdgeMqttServerDto) (*EdgeMqttServerDto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMqttServers not implemented")
}

func RegisterEdgeApiServiceServer(s *grpc.Server, srv EdgeApiServiceServer) {
	s.RegisterService(&_EdgeApiService_serviceDesc, srv)
}

func _EdgeApiService_GetMqttServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EdgeMqttServerDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeApiServiceServer).GetMqttServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbgocmd.EdgeApiService/GetMqttServers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeApiServiceServer).GetMqttServers(ctx, req.(*EdgeMqttServerDto))
	}
	return interceptor(ctx, in, info, handler)
}

var _EdgeApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbgocmd.EdgeApiService",
	HandlerType: (*EdgeApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getMqttServers",
			Handler:    _EdgeApiService_GetMqttServers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "edgeServer.proto",
}
