// Code generated by protoc-gen-go. DO NOT EDIT.
// source: edgeServer.proto

package pbgocmd

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_struct "github.com/golang/protobuf/ptypes/struct"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Struct from public import google/protobuf/struct.proto
type Struct = _struct.Struct

// Value from public import google/protobuf/struct.proto
type Value = _struct.Value
type Value_NullValue = _struct.Value_NullValue
type Value_NumberValue = _struct.Value_NumberValue
type Value_StringValue = _struct.Value_StringValue
type Value_BoolValue = _struct.Value_BoolValue
type Value_StructValue = _struct.Value_StructValue
type Value_ListValue = _struct.Value_ListValue

// ListValue from public import google/protobuf/struct.proto
type ListValue = _struct.ListValue

// NullValue from public import google/protobuf/struct.proto
type NullValue = _struct.NullValue

var NullValue_name = _struct.NullValue_name
var NullValue_value = _struct.NullValue_value

const NullValue_NULL_VALUE = NullValue(_struct.NullValue_NULL_VALUE)

// Any from public import google/protobuf/any.proto
type Any = any.Any

type GateWayType int32

const (
	GateWayType_Unknow               GateWayType = 0
	GateWayType_MqttGateWay          GateWayType = 1
	GateWayType_MqttWebsocketGateWay GateWayType = 2
	GateWayType_GrpcGateWay          GateWayType = 3
	GateWayType_TcpGateWay           GateWayType = 4
)

var GateWayType_name = map[int32]string{
	0: "Unknow",
	1: "MqttGateWay",
	2: "MqttWebsocketGateWay",
	3: "GrpcGateWay",
	4: "TcpGateWay",
}

var GateWayType_value = map[string]int32{
	"Unknow":               0,
	"MqttGateWay":          1,
	"MqttWebsocketGateWay": 2,
	"GrpcGateWay":          3,
	"TcpGateWay":           4,
}

func (x GateWayType) String() string {
	return proto.EnumName(GateWayType_name, int32(x))
}

func (GateWayType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_863328f2236aab81, []int{0}
}

type NorthProtoMsg struct {
	Success      bool   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	//  bytes Data = 3;
	Data                 *any.Any `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NorthProtoMsg) Reset()         { *m = NorthProtoMsg{} }
func (m *NorthProtoMsg) String() string { return proto.CompactTextString(m) }
func (*NorthProtoMsg) ProtoMessage()    {}
func (*NorthProtoMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_863328f2236aab81, []int{0}
}

func (m *NorthProtoMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NorthProtoMsg.Unmarshal(m, b)
}
func (m *NorthProtoMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NorthProtoMsg.Marshal(b, m, deterministic)
}
func (m *NorthProtoMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NorthProtoMsg.Merge(m, src)
}
func (m *NorthProtoMsg) XXX_Size() int {
	return xxx_messageInfo_NorthProtoMsg.Size(m)
}
func (m *NorthProtoMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NorthProtoMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NorthProtoMsg proto.InternalMessageInfo

func (m *NorthProtoMsg) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *NorthProtoMsg) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *NorthProtoMsg) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type TlsConfig struct {
	Enable               bool     `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
	SkipVerify           bool     `protobuf:"varint,3,opt,name=skipVerify,proto3" json:"skipVerify,omitempty"`
	ServerCaCert         []byte   `protobuf:"bytes,4,opt,name=serverCaCert,proto3" json:"serverCaCert,omitempty"`
	ClientCaCert         []byte   `protobuf:"bytes,5,opt,name=clientCaCert,proto3" json:"clientCaCert,omitempty"`
	ClientCert           []byte   `protobuf:"bytes,6,opt,name=clientCert,proto3" json:"clientCert,omitempty"`
	ClientCertKey        []byte   `protobuf:"bytes,7,opt,name=clientCertKey,proto3" json:"clientCertKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TlsConfig) Reset()         { *m = TlsConfig{} }
func (m *TlsConfig) String() string { return proto.CompactTextString(m) }
func (*TlsConfig) ProtoMessage()    {}
func (*TlsConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_863328f2236aab81, []int{1}
}

func (m *TlsConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TlsConfig.Unmarshal(m, b)
}
func (m *TlsConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TlsConfig.Marshal(b, m, deterministic)
}
func (m *TlsConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TlsConfig.Merge(m, src)
}
func (m *TlsConfig) XXX_Size() int {
	return xxx_messageInfo_TlsConfig.Size(m)
}
func (m *TlsConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TlsConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TlsConfig proto.InternalMessageInfo

func (m *TlsConfig) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *TlsConfig) GetSkipVerify() bool {
	if m != nil {
		return m.SkipVerify
	}
	return false
}

func (m *TlsConfig) GetServerCaCert() []byte {
	if m != nil {
		return m.ServerCaCert
	}
	return nil
}

func (m *TlsConfig) GetClientCaCert() []byte {
	if m != nil {
		return m.ClientCaCert
	}
	return nil
}

func (m *TlsConfig) GetClientCert() []byte {
	if m != nil {
		return m.ClientCert
	}
	return nil
}

func (m *TlsConfig) GetClientCertKey() []byte {
	if m != nil {
		return m.ClientCertKey
	}
	return nil
}

type EdgeMqttServerDto struct {
	Addr                 string     `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Port                 int32      `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username             string     `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Passwd               string     `protobuf:"bytes,4,opt,name=passwd,proto3" json:"passwd,omitempty"`
	CliId                string     `protobuf:"bytes,5,opt,name=cliId,proto3" json:"cliId,omitempty"`
	Tls                  *TlsConfig `protobuf:"bytes,6,opt,name=tls,proto3" json:"tls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EdgeMqttServerDto) Reset()         { *m = EdgeMqttServerDto{} }
func (m *EdgeMqttServerDto) String() string { return proto.CompactTextString(m) }
func (*EdgeMqttServerDto) ProtoMessage()    {}
func (*EdgeMqttServerDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_863328f2236aab81, []int{2}
}

func (m *EdgeMqttServerDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdgeMqttServerDto.Unmarshal(m, b)
}
func (m *EdgeMqttServerDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdgeMqttServerDto.Marshal(b, m, deterministic)
}
func (m *EdgeMqttServerDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeMqttServerDto.Merge(m, src)
}
func (m *EdgeMqttServerDto) XXX_Size() int {
	return xxx_messageInfo_EdgeMqttServerDto.Size(m)
}
func (m *EdgeMqttServerDto) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeMqttServerDto.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeMqttServerDto proto.InternalMessageInfo

func (m *EdgeMqttServerDto) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *EdgeMqttServerDto) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *EdgeMqttServerDto) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *EdgeMqttServerDto) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *EdgeMqttServerDto) GetCliId() string {
	if m != nil {
		return m.CliId
	}
	return ""
}

func (m *EdgeMqttServerDto) GetTls() *TlsConfig {
	if m != nil {
		return m.Tls
	}
	return nil
}

type ServerInfo struct {
	// Types that are valid to be assigned to Kind:
	//	*ServerInfo_MqttServer
	Kind                 isServerInfo_Kind `protobuf_oneof:"kind"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ServerInfo) Reset()         { *m = ServerInfo{} }
func (m *ServerInfo) String() string { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()    {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_863328f2236aab81, []int{3}
}

func (m *ServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfo.Unmarshal(m, b)
}
func (m *ServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfo.Marshal(b, m, deterministic)
}
func (m *ServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfo.Merge(m, src)
}
func (m *ServerInfo) XXX_Size() int {
	return xxx_messageInfo_ServerInfo.Size(m)
}
func (m *ServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfo proto.InternalMessageInfo

type isServerInfo_Kind interface {
	isServerInfo_Kind()
}

type ServerInfo_MqttServer struct {
	MqttServer *EdgeMqttServerDto `protobuf:"bytes,1,opt,name=mqttServer,proto3,oneof"`
}

func (*ServerInfo_MqttServer) isServerInfo_Kind() {}

func (m *ServerInfo) GetKind() isServerInfo_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *ServerInfo) GetMqttServer() *EdgeMqttServerDto {
	if x, ok := m.GetKind().(*ServerInfo_MqttServer); ok {
		return x.MqttServer
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerInfo) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerInfo_MqttServer)(nil),
	}
}

//
type EdgeServerDto struct {
	Id         int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerType GateWayType `protobuf:"varint,2,opt,name=serverType,proto3,enum=edgemsg.GateWayType" json:"serverType,omitempty"`
	Enable     bool        `protobuf:"varint,3,opt,name=enable,proto3" json:"enable,omitempty"`
	//  google.protobuf.Struct serverInfo = 4;
	ServerInfo           *ServerInfo `protobuf:"bytes,4,opt,name=ServerInfo,proto3" json:"ServerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EdgeServerDto) Reset()         { *m = EdgeServerDto{} }
func (m *EdgeServerDto) String() string { return proto.CompactTextString(m) }
func (*EdgeServerDto) ProtoMessage()    {}
func (*EdgeServerDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_863328f2236aab81, []int{4}
}

func (m *EdgeServerDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdgeServerDto.Unmarshal(m, b)
}
func (m *EdgeServerDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdgeServerDto.Marshal(b, m, deterministic)
}
func (m *EdgeServerDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeServerDto.Merge(m, src)
}
func (m *EdgeServerDto) XXX_Size() int {
	return xxx_messageInfo_EdgeServerDto.Size(m)
}
func (m *EdgeServerDto) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeServerDto.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeServerDto proto.InternalMessageInfo

func (m *EdgeServerDto) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EdgeServerDto) GetServerType() GateWayType {
	if m != nil {
		return m.ServerType
	}
	return GateWayType_Unknow
}

func (m *EdgeServerDto) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *EdgeServerDto) GetServerInfo() *ServerInfo {
	if m != nil {
		return m.ServerInfo
	}
	return nil
}

type EdgeGaywayOnlineReq struct {
	EdgeGaywayId         string   `protobuf:"bytes,1,opt,name=edgeGaywayId,proto3" json:"edgeGaywayId,omitempty"`
	DeviceModel          string   `protobuf:"bytes,2,opt,name=deviceModel,proto3" json:"deviceModel,omitempty"`
	HardVersion          string   `protobuf:"bytes,3,opt,name=hardVersion,proto3" json:"hardVersion,omitempty"`
	SoftVersion          string   `protobuf:"bytes,4,opt,name=softVersion,proto3" json:"softVersion,omitempty"`
	TunnelSupport        []string `protobuf:"bytes,5,rep,name=tunnelSupport,proto3" json:"tunnelSupport,omitempty"`
	NotBefore            int64    `protobuf:"varint,6,opt,name=notBefore,proto3" json:"notBefore,omitempty"`
	NotAfter             int64    `protobuf:"varint,7,opt,name=notAfter,proto3" json:"notAfter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EdgeGaywayOnlineReq) Reset()         { *m = EdgeGaywayOnlineReq{} }
func (m *EdgeGaywayOnlineReq) String() string { return proto.CompactTextString(m) }
func (*EdgeGaywayOnlineReq) ProtoMessage()    {}
func (*EdgeGaywayOnlineReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_863328f2236aab81, []int{5}
}

func (m *EdgeGaywayOnlineReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdgeGaywayOnlineReq.Unmarshal(m, b)
}
func (m *EdgeGaywayOnlineReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdgeGaywayOnlineReq.Marshal(b, m, deterministic)
}
func (m *EdgeGaywayOnlineReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeGaywayOnlineReq.Merge(m, src)
}
func (m *EdgeGaywayOnlineReq) XXX_Size() int {
	return xxx_messageInfo_EdgeGaywayOnlineReq.Size(m)
}
func (m *EdgeGaywayOnlineReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeGaywayOnlineReq.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeGaywayOnlineReq proto.InternalMessageInfo

func (m *EdgeGaywayOnlineReq) GetEdgeGaywayId() string {
	if m != nil {
		return m.EdgeGaywayId
	}
	return ""
}

func (m *EdgeGaywayOnlineReq) GetDeviceModel() string {
	if m != nil {
		return m.DeviceModel
	}
	return ""
}

func (m *EdgeGaywayOnlineReq) GetHardVersion() string {
	if m != nil {
		return m.HardVersion
	}
	return ""
}

func (m *EdgeGaywayOnlineReq) GetSoftVersion() string {
	if m != nil {
		return m.SoftVersion
	}
	return ""
}

func (m *EdgeGaywayOnlineReq) GetTunnelSupport() []string {
	if m != nil {
		return m.TunnelSupport
	}
	return nil
}

func (m *EdgeGaywayOnlineReq) GetNotBefore() int64 {
	if m != nil {
		return m.NotBefore
	}
	return 0
}

func (m *EdgeGaywayOnlineReq) GetNotAfter() int64 {
	if m != nil {
		return m.NotAfter
	}
	return 0
}

type EdgeGaywayReq struct {
	EdgeGaywayId         string   `protobuf:"bytes,1,opt,name=edgeGaywayId,proto3" json:"edgeGaywayId,omitempty"`
	ProjectId            string   `protobuf:"bytes,2,opt,name=projectId,proto3" json:"projectId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EdgeGaywayReq) Reset()         { *m = EdgeGaywayReq{} }
func (m *EdgeGaywayReq) String() string { return proto.CompactTextString(m) }
func (*EdgeGaywayReq) ProtoMessage()    {}
func (*EdgeGaywayReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_863328f2236aab81, []int{6}
}

func (m *EdgeGaywayReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdgeGaywayReq.Unmarshal(m, b)
}
func (m *EdgeGaywayReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdgeGaywayReq.Marshal(b, m, deterministic)
}
func (m *EdgeGaywayReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeGaywayReq.Merge(m, src)
}
func (m *EdgeGaywayReq) XXX_Size() int {
	return xxx_messageInfo_EdgeGaywayReq.Size(m)
}
func (m *EdgeGaywayReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeGaywayReq.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeGaywayReq proto.InternalMessageInfo

func (m *EdgeGaywayReq) GetEdgeGaywayId() string {
	if m != nil {
		return m.EdgeGaywayId
	}
	return ""
}

func (m *EdgeGaywayReq) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func init() {
	proto.RegisterEnum("edgemsg.GateWayType", GateWayType_name, GateWayType_value)
	proto.RegisterType((*NorthProtoMsg)(nil), "edgemsg.NorthProtoMsg")
	proto.RegisterType((*TlsConfig)(nil), "edgemsg.TlsConfig")
	proto.RegisterType((*EdgeMqttServerDto)(nil), "edgemsg.EdgeMqttServerDto")
	proto.RegisterType((*ServerInfo)(nil), "edgemsg.ServerInfo")
	proto.RegisterType((*EdgeServerDto)(nil), "edgemsg.EdgeServerDto")
	proto.RegisterType((*EdgeGaywayOnlineReq)(nil), "edgemsg.EdgeGaywayOnlineReq")
	proto.RegisterType((*EdgeGaywayReq)(nil), "edgemsg.EdgeGaywayReq")
}

func init() { proto.RegisterFile("edgeServer.proto", fileDescriptor_863328f2236aab81) }

var fileDescriptor_863328f2236aab81 = []byte{
	// 698 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x6f, 0xda, 0x48,
	0x14, 0xc5, 0x18, 0x08, 0xbe, 0x4e, 0xd8, 0xec, 0x04, 0xad, 0x58, 0x14, 0xad, 0x90, 0x95, 0x07,
	0xb4, 0x0f, 0x44, 0x22, 0xfb, 0xb6, 0xfb, 0x92, 0x2f, 0x65, 0x69, 0x45, 0x9b, 0x4e, 0xd2, 0x44,
	0xaa, 0xfa, 0x62, 0xec, 0x8b, 0xe3, 0xe2, 0xcc, 0x38, 0x33, 0x43, 0x90, 0xff, 0x4e, 0x5f, 0xfb,
	0x6b, 0xfa, 0x8b, 0x5a, 0xcd, 0xd8, 0x18, 0xd3, 0x4a, 0x51, 0xdf, 0x7c, 0xce, 0x3d, 0x99, 0xb9,
	0x67, 0xce, 0x09, 0xb0, 0x8f, 0x61, 0x84, 0x37, 0x28, 0x9e, 0x51, 0x8c, 0x52, 0xc1, 0x15, 0x27,
	0x3b, 0x9a, 0x79, 0x94, 0x51, 0xff, 0x30, 0xe2, 0x3c, 0x4a, 0xf0, 0xd8, 0xd0, 0xb3, 0xe5, 0xfc,
	0x58, 0x2a, 0xb1, 0x0c, 0x54, 0x2e, 0xeb, 0xff, 0xf9, 0xe3, 0xd4, 0x67, 0x59, 0x3e, 0xf2, 0x56,
	0xb0, 0xf7, 0x86, 0x0b, 0xf5, 0x70, 0xad, 0xd1, 0x54, 0x46, 0xa4, 0x07, 0x3b, 0x37, 0xcb, 0x20,
	0x40, 0x29, 0x7b, 0xd6, 0xc0, 0x1a, 0xb6, 0xe9, 0x1a, 0x12, 0x0f, 0x76, 0x2f, 0x85, 0xe0, 0x62,
	0x8a, 0x52, 0xfa, 0x11, 0xf6, 0xea, 0x03, 0x6b, 0xe8, 0xd0, 0x2d, 0x8e, 0x0c, 0xa1, 0x71, 0xe1,
	0x2b, 0xbf, 0x67, 0x0f, 0xac, 0xa1, 0x3b, 0xee, 0x8e, 0xf2, 0x8b, 0x47, 0xeb, 0x8b, 0x47, 0xa7,
	0x2c, 0xa3, 0x46, 0xe1, 0x7d, 0xb5, 0xc0, 0xb9, 0x4d, 0xe4, 0x39, 0x67, 0xf3, 0x38, 0x22, 0x7f,
	0x40, 0x0b, 0x99, 0x3f, 0x4b, 0xf2, 0x53, 0xdb, 0xb4, 0x40, 0xe4, 0x2f, 0x00, 0xb9, 0x88, 0xd3,
	0x3b, 0x14, 0xf1, 0x3c, 0x33, 0xa7, 0xb6, 0x69, 0x85, 0xd1, 0x3b, 0x49, 0xf3, 0x20, 0xe7, 0xfe,
	0x39, 0x0a, 0xd5, 0x6b, 0x0c, 0xac, 0xe1, 0x2e, 0xdd, 0xe2, 0xb4, 0x26, 0x48, 0x62, 0x64, 0xaa,
	0xd0, 0x34, 0x73, 0x4d, 0x95, 0xd3, 0xf7, 0x14, 0x58, 0x2b, 0x5a, 0x46, 0x51, 0x61, 0xc8, 0x11,
	0xec, 0x6d, 0xd0, 0x6b, 0xcc, 0x7a, 0x3b, 0x46, 0xb2, 0x4d, 0x7a, 0x5f, 0x2c, 0xf8, 0xfd, 0x32,
	0x8c, 0x70, 0xfa, 0xa4, 0x54, 0x9e, 0xd3, 0x85, 0xe2, 0x84, 0x40, 0xc3, 0x0f, 0x43, 0x61, 0x9e,
	0xd3, 0xa1, 0xe6, 0x5b, 0x73, 0x29, 0x17, 0xca, 0xb8, 0x6d, 0x52, 0xf3, 0x4d, 0xfa, 0xd0, 0x5e,
	0x4a, 0x14, 0xcc, 0x7f, 0x44, 0xe3, 0xd4, 0xa1, 0x25, 0xd6, 0xef, 0x93, 0xfa, 0x52, 0xae, 0x42,
	0xe3, 0xd0, 0xa1, 0x05, 0x22, 0x5d, 0x68, 0x06, 0x49, 0x3c, 0x09, 0x8d, 0x29, 0x87, 0xe6, 0x80,
	0x1c, 0x81, 0xad, 0x12, 0x69, 0x6c, 0xb8, 0x63, 0x32, 0x2a, 0x4a, 0x32, 0x2a, 0x9f, 0x9b, 0xea,
	0xb1, 0x47, 0x01, 0xf2, 0x25, 0x27, 0x6c, 0xce, 0xc9, 0x7f, 0x00, 0x8f, 0xe5, 0xda, 0x66, 0x57,
	0x77, 0xdc, 0x2f, 0xff, 0xf4, 0x27, 0x57, 0xff, 0xd7, 0x68, 0x45, 0x7f, 0xd6, 0x82, 0xc6, 0x22,
	0x66, 0xa1, 0xf7, 0xd9, 0x82, 0xbd, 0xcb, 0xb2, 0xa5, 0xda, 0x7d, 0x07, 0xea, 0x71, 0x68, 0xce,
	0xb3, 0x69, 0x3d, 0x0e, 0xc9, 0x3f, 0x00, 0x79, 0x3a, 0xb7, 0x59, 0x9a, 0xa7, 0xdd, 0x19, 0x77,
	0xcb, 0x7b, 0xae, 0x7c, 0x85, 0xf7, 0x7e, 0xa6, 0x67, 0xb4, 0xa2, 0xab, 0xf4, 0xc3, 0xde, 0xea,
	0xc7, 0x49, 0xd5, 0x83, 0x79, 0x1b, 0x77, 0x7c, 0x50, 0x9e, 0xb6, 0x19, 0xd1, 0x8a, 0xcc, 0xfb,
	0x66, 0xc1, 0x81, 0x5e, 0xf2, 0xca, 0xcf, 0x56, 0x7e, 0xf6, 0x96, 0x25, 0x31, 0x43, 0x8a, 0x4f,
	0xba, 0x28, 0x58, 0xd2, 0x93, 0xb0, 0x08, 0x6c, 0x8b, 0x23, 0x03, 0x70, 0x43, 0x7c, 0x8e, 0x03,
	0x9c, 0xf2, 0x10, 0x93, 0xe2, 0x7f, 0xa0, 0x4a, 0x69, 0xc5, 0x83, 0x2f, 0xc2, 0x3b, 0x14, 0x32,
	0xe6, 0xac, 0x48, 0xb2, 0x4a, 0x69, 0x85, 0xe4, 0x73, 0xb5, 0x56, 0xe4, 0x89, 0x56, 0x29, 0x5d,
	0x37, 0xb5, 0x64, 0x0c, 0x93, 0x9b, 0x65, 0x6a, 0x7a, 0xd2, 0x1c, 0xd8, 0x43, 0x87, 0x6e, 0x93,
	0xe4, 0x10, 0x1c, 0xc6, 0xd5, 0x19, 0xce, 0xb9, 0x40, 0x13, 0xb6, 0x4d, 0x37, 0x84, 0xae, 0x13,
	0xe3, 0xea, 0x74, 0xae, 0x50, 0x98, 0xb6, 0xda, 0xb4, 0xc4, 0xde, 0xbb, 0x3c, 0xa5, 0xdc, 0xd5,
	0xaf, 0x5a, 0x3f, 0x04, 0x27, 0x15, 0xfc, 0x13, 0x06, 0x6a, 0x12, 0x16, 0xc6, 0x37, 0xc4, 0xdf,
	0x08, 0x6e, 0x25, 0x3c, 0x02, 0xd0, 0x7a, 0xcf, 0x16, 0x8c, 0xaf, 0xf6, 0x6b, 0xe4, 0x37, 0x70,
	0x75, 0x77, 0x8a, 0xf1, 0xbe, 0x45, 0x7a, 0xd0, 0xd5, 0xc4, 0x3d, 0xce, 0x24, 0x0f, 0x16, 0x58,
	0x4e, 0xea, 0x5a, 0x7a, 0x25, 0xd2, 0x60, 0x4d, 0xd8, 0xa4, 0x03, 0x70, 0x1b, 0xa4, 0x6b, 0xdc,
	0x18, 0x7f, 0x84, 0x8e, 0xde, 0xfc, 0x34, 0x8d, 0x75, 0xa0, 0x71, 0x80, 0xe4, 0x15, 0x74, 0x22,
	0x54, 0x9b, 0x72, 0x4a, 0xf2, 0x42, 0x6d, 0xfb, 0x2f, 0xcc, 0xbc, 0xda, 0x99, 0xfb, 0xc1, 0x19,
	0xfd, 0x5b, 0x08, 0xae, 0x6b, 0xd7, 0xd6, 0xac, 0x65, 0x7e, 0xb9, 0x4e, 0xbe, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x12, 0x92, 0x69, 0xcb, 0x7b, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EdgeApiServiceClient is the client API for EdgeApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EdgeApiServiceClient interface {
	// 获取mqtt服务器信息
	GetMqttServers(ctx context.Context, in *EdgeMqttServerDto, opts ...grpc.CallOption) (*EdgeMqttServerDto, error)
}

type edgeApiServiceClient struct {
	cc *grpc.ClientConn
}

func NewEdgeApiServiceClient(cc *grpc.ClientConn) EdgeApiServiceClient {
	return &edgeApiServiceClient{cc}
}

func (c *edgeApiServiceClient) GetMqttServers(ctx context.Context, in *EdgeMqttServerDto, opts ...grpc.CallOption) (*EdgeMqttServerDto, error) {
	out := new(EdgeMqttServerDto)
	err := c.cc.Invoke(ctx, "/edgemsg.EdgeApiService/getMqttServers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdgeApiServiceServer is the server API for EdgeApiService service.
type EdgeApiServiceServer interface {
	// 获取mqtt服务器信息
	GetMqttServers(context.Context, *EdgeMqttServerDto) (*EdgeMqttServerDto, error)
}

// UnimplementedEdgeApiServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEdgeApiServiceServer struct {
}

func (*UnimplementedEdgeApiServiceServer) GetMqttServers(ctx context.Context, req *EdgeMqttServerDto) (*EdgeMqttServerDto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMqttServers not implemented")
}

func RegisterEdgeApiServiceServer(s *grpc.Server, srv EdgeApiServiceServer) {
	s.RegisterService(&_EdgeApiService_serviceDesc, srv)
}

func _EdgeApiService_GetMqttServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EdgeMqttServerDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeApiServiceServer).GetMqttServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edgemsg.EdgeApiService/GetMqttServers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeApiServiceServer).GetMqttServers(ctx, req.(*EdgeMqttServerDto))
	}
	return interceptor(ctx, in, info, handler)
}

var _EdgeApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "edgemsg.EdgeApiService",
	HandlerType: (*EdgeApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getMqttServers",
			Handler:    _EdgeApiService_GetMqttServers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "edgeServer.proto",
}
