// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxyMsg.proto

package pbgocmd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MqttProxyMessage struct {
	Head                 *MessageHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Src                  string       `protobuf:"bytes,2,opt,name=Src,proto3" json:"Src,omitempty"`
	Dst                  string       `protobuf:"bytes,3,opt,name=Dst,proto3" json:"Dst,omitempty"`
	Data                 []byte       `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MqttProxyMessage) Reset()         { *m = MqttProxyMessage{} }
func (m *MqttProxyMessage) String() string { return proto.CompactTextString(m) }
func (*MqttProxyMessage) ProtoMessage()    {}
func (*MqttProxyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e1de33eb5a1ade, []int{0}
}

func (m *MqttProxyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MqttProxyMessage.Unmarshal(m, b)
}
func (m *MqttProxyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MqttProxyMessage.Marshal(b, m, deterministic)
}
func (m *MqttProxyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MqttProxyMessage.Merge(m, src)
}
func (m *MqttProxyMessage) XXX_Size() int {
	return xxx_messageInfo_MqttProxyMessage.Size(m)
}
func (m *MqttProxyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MqttProxyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MqttProxyMessage proto.InternalMessageInfo

func (m *MqttProxyMessage) GetHead() *MessageHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *MqttProxyMessage) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *MqttProxyMessage) GetDst() string {
	if m != nil {
		return m.Dst
	}
	return ""
}

func (m *MqttProxyMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*MqttProxyMessage)(nil), "edgemsg.MqttProxyMessage")
}

func init() { proto.RegisterFile("proxyMsg.proto", fileDescriptor_14e1de33eb5a1ade) }

var fileDescriptor_14e1de33eb5a1ade = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0xaf,
	0xa8, 0xf4, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x4d, 0x49, 0x4f,
	0xcd, 0x2d, 0x4e, 0x97, 0x12, 0x48, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0x81, 0x4b, 0x29, 0x95,
	0x70, 0x09, 0xf8, 0x16, 0x96, 0x94, 0x04, 0x80, 0x35, 0xa4, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x0a,
	0x69, 0x70, 0xb1, 0x64, 0xa4, 0x26, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x89, 0xe8,
	0x41, 0x75, 0xeb, 0x41, 0xe5, 0x3d, 0x52, 0x13, 0x53, 0x82, 0xc0, 0x2a, 0x84, 0x04, 0xb8, 0x98,
	0x83, 0x8b, 0x92, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x90, 0x88, 0x4b, 0x71,
	0x89, 0x04, 0x33, 0x44, 0xc4, 0xa5, 0xb8, 0x44, 0x48, 0x88, 0x8b, 0xc5, 0x25, 0xb1, 0x24, 0x51,
	0x82, 0x45, 0x81, 0x51, 0x83, 0x27, 0x08, 0xcc, 0x76, 0x52, 0xe7, 0x12, 0xcd, 0xcc, 0x2f, 0xd1,
	0x2b, 0xc8, 0xd4, 0x4b, 0x2a, 0xca, 0xcf, 0x4e, 0x2d, 0xd2, 0x83, 0xba, 0x2b, 0x80, 0x31, 0x8a,
	0x53, 0xcf, 0x1a, 0x6a, 0x5f, 0x07, 0x23, 0x63, 0x12, 0x1b, 0xd8, 0x95, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x57, 0x4e, 0xed, 0xef, 0xd2, 0x00, 0x00, 0x00,
}
