// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.0
// source: proxyMsg.proto

package pbgocmd

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MqttProxyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *MessageHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"` // 通用消息头
	Src  string       `protobuf:"bytes,2,opt,name=Src,proto3" json:"Src,omitempty"`   // 源地址
	Dst  string       `protobuf:"bytes,3,opt,name=Dst,proto3" json:"Dst,omitempty"`   // 目的地址
	Data []byte       `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"` // 数据
}

func (x *MqttProxyMessage) Reset() {
	*x = MqttProxyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxyMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MqttProxyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MqttProxyMessage) ProtoMessage() {}

func (x *MqttProxyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proxyMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MqttProxyMessage.ProtoReflect.Descriptor instead.
func (*MqttProxyMessage) Descriptor() ([]byte, []int) {
	return file_proxyMsg_proto_rawDescGZIP(), []int{0}
}

func (x *MqttProxyMessage) GetHead() *MessageHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *MqttProxyMessage) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *MqttProxyMessage) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *MqttProxyMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proxyMsg_proto protoreflect.FileDescriptor

var file_proxyMsg_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x1a, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x74, 0x0a, 0x10, 0x4d,
	0x71, 0x74, 0x74, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x28, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x70, 0x62, 0x67, 0x6f, 0x63, 0x6d, 0x64, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x72, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x44,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x44, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x42, 0x23, 0x0a, 0x11, 0x74, 0x6f, 0x70, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x78, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x50, 0x01, 0x5a, 0x09, 0x2e, 0x3b, 0x70, 0x62, 0x67, 0x6f,
	0x63, 0x6d, 0x64, 0x88, 0x01, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proxyMsg_proto_rawDescOnce sync.Once
	file_proxyMsg_proto_rawDescData = file_proxyMsg_proto_rawDesc
)

func file_proxyMsg_proto_rawDescGZIP() []byte {
	file_proxyMsg_proto_rawDescOnce.Do(func() {
		file_proxyMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_proxyMsg_proto_rawDescData)
	})
	return file_proxyMsg_proto_rawDescData
}

var file_proxyMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proxyMsg_proto_goTypes = []interface{}{
	(*MqttProxyMessage)(nil), // 0: pbgocmd.MqttProxyMessage
	(*MessageHead)(nil),      // 1: pbgocmd.MessageHead
}
var file_proxyMsg_proto_depIdxs = []int32{
	1, // 0: pbgocmd.MqttProxyMessage.head:type_name -> pbgocmd.MessageHead
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proxyMsg_proto_init() }
func file_proxyMsg_proto_init() {
	if File_proxyMsg_proto != nil {
		return
	}
	file_commandMsg_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proxyMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MqttProxyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proxyMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxyMsg_proto_goTypes,
		DependencyIndexes: file_proxyMsg_proto_depIdxs,
		MessageInfos:      file_proxyMsg_proto_msgTypes,
	}.Build()
	File_proxyMsg_proto = out.File
	file_proxyMsg_proto_rawDesc = nil
	file_proxyMsg_proto_goTypes = nil
	file_proxyMsg_proto_depIdxs = nil
}
